### ISSUE TITLE
Wrangle `z-index` rules

### ISSUE THREAD

**Issue by ericf** [yahoo/pure#106]
We should have a good understanding of Pure's `z-index` rules and how they play with each other between modules.

**Comment by jamesalley** [comment]
Surveyed z-index in Pure and found six instances: 

```
build$ grep "z-index" *[!-min.css].css
forms-nr.css:    z-index: 2;
menus-nr.css:    z-index: 2;
pure-nr.css:    z-index: 2;
pure-nr.css:    z-index: 2;
pure.css:    z-index: 2;
pure.css:    z-index: 2;
```

So we don't have a big z-index management issue here. Still, we could simply use z-index 3 and it would avoid the problem we saw with the original issue. I'll leave this issue open.

**Comment by jamesalley** [comment]
All z-index instances (of which there were only a few) have been bumped to `z-index: 3`. This will appear in the next release, Pure 0.6.
