### ISSUE TITLE
Make it easier to customize menus

### ISSUE THREAD

**Issue by tilomitra** [yahoo/pure#107]
Styling menus are a pain. I would love to have it be as simple as styling buttons (basically, needing to go off only one element to style it). One of the reasons it's painful to style is because the styles and the DOM tree were initially borrowed from Y.Menu. 

I propose starting from scratch to see what the simplest possible DOM structure would look like for a menu, and then think of JS integration. I think a simpler DOM + less class names + less direct descendent selectors would make menus easier to customize.

**Comment by zbyte64** [comment]
See #424 (New Menu for 0.6.0)

**Comment by jamesalley** [comment]
I guess I can close this issue, as I've ended up doing just what is discussed here. "New Menu" is out there (at least on http://stage.purecss.io) in the RC (release candidate) for Pure 0.6.0. It's certainly easier to customize. The YUI connection has been cut. I'm sure there will be new issues, questions, and proposed enhancements, but we can file those as new GitHub issues.

**Comment by jharaphula** [comment]
In this example I have tabs like Home, About Us, Services, News & Career. You can add or update tags as you want. This menu is supporting sub menu feature. Under About Us & Services I added some sub menu items for demo purpose. Technically to design this horizontal menu I used UL element of HTML. Using pure CSS I am defining color & theme to the menu. For responsive I used CSS3 media queries. In media query I configured the menu max-width to 750px. 750px is nothing but the total width of my horizontal menu (including all tabs)... https://goo.gl/VwTusI
