### ISSUE TITLE
Button groups

### ISSUE THREAD

**Issue by joepie91** [yahoo/pure#126]
I quite love Pure so far, but there's one quite important feature that's missing: button groups. Both [HTML Kickstart](http://www.99lime.com/elements/) and [Bootstrap](http://twitter.github.io/bootstrap/components.html#buttonGroups) already implement this, and it's a quite important (and intuitive!) part for the UI of more complex applications, in particular data-driven ones.

Are there any plans to add this in the near future?

**Comment by redonkulus** [comment]
Merged in #621
