### ISSUE TITLE
Add an Animations module

### ISSUE THREAD

**Issue by AurelioDeRosa** [yahoo/pure#141]
I think that would be great to add a small Animations module. Something simple but nice to follow the line of other modules that can be used standalone or with other modules, especially the Buttons module. I was thinking something like flipping, fading, revealing and so on.

Any thoughts?

**Comment by jamesalley** [comment]
Animations are an extremely complex topic, with lots of options at our disposal. To me, animations are too opinionated to include in Pure by default. Some boilerplate effects could be nice as part of a broader component library. Menu notwithstanding, Pure is not a component library; it is a ridiculously tiny starting point for any web project, and should be as transparent and un-opinionated as possible.
