### ISSUE TITLE
Vertical alignment of labels for textboxes

### ISSUE THREAD

**Issue by joepie91** [yahoo/pure#163]
When using a label with a &lt;textarea&gt; in a pure-form-aligned, the label is still vertically centered (as with other form elements). UX-wise, it would be strongly preferable to top-align the label in the case of a tall form element such as a &lt;textarea&gt;.

Example case of what it looks like now:

```html
<form class="pure-form pure-form-aligned form_createnode">
	<div class="pure-control-group">
		<label for="input_createnode_name">Name</label>
		<input type="text" name="name" id="input_createnode_name">
	</div>
	
	<div class="pure-control-group">
		<label for="input_createnode_notes">Notes</label>
		<textarea name="notes" id="input_createnode_notes"></textarea>
	</div>
</form>

```

![original_owely20130814-10506-1pfo6cp](https://f.cloud.github.com/assets/1663259/959499/80f7f6a4-048a-11e3-8c61-62d9381633c5.png)

**Comment by jamesalley** [comment]
I'm not convinced that everyone would want this by default. Furthermore, this is easily resolved with a custom class applied to the label. This is a fine customization for a user to do themselves. While we could create a "pure-form-align-top" class or something like that, we run the risk of adding something that not all users will need, and then we have to document it and make the feature discoverable...which is problematic. For instance, if we added such a class to Pure, and a user hadn't noticed it in the documentation, they might go ahead and add their own custom class anyway. I think that scenario is highly likely, and in that case their code would not be DRY, there would be two classes which do the same thing.

This is a minor enhancement which I think can safely be omitted from Pure. Feel free to add more comments and reopen if you disagree!
