### ISSUE TITLE
<select> looks out of place in Firefox on Mac OS X

### ISSUE THREAD

**Issue by tp** [yahoo/pure#167]
I just came about a site using pure in forms, and was immediately irritated by the appearance of the `select` element.

How come it looks like Windows XP in Firefox, albeit fine in Chrome and Safari?
Chrome 28:
![purecss select chrome 28](https://f.cloud.github.com/assets/52437/1001195/9375d0a6-0a63-11e3-9b20-17df81a984d8.png)
Firefox 23:
![purecss select firefox 23 0 1](https://f.cloud.github.com/assets/52437/1001196/93c6365e-0a63-11e3-9192-3d444c03a0e3.png)
(Screenshots of http://purecss.io/forms/)

**Comment by jamesalley** [comment]
I did work on this, having noticed it independently. I have given the select element some default height in an attempt to make it more consistent across browsers; padding is not honored in the select element, and that was what was used to size the other elements.
