### ISSUE TITLE
Adding styles for input append and input prepend

### ISSUE THREAD

**Issue by levelnis** [yahoo/pure#187]
Are there any plans to add styles for appending/prepending elements within form inputs? I can see some classes in the yui-site partials (pure-input-prepend and pure-input-append) but those classes don't seem to have made it in to 0.2.1 or 0.3 unless I've missed something?

I'm replacing Bootstrap with Pure in my site and that was one feature we used on the forms that I'll need to replicate (manually at present)

**Comment by jamesalley** [comment]
Closing as we have a duplicate issue open, https://github.com/yahoo/pure/issues/239
