### ISSUE TITLE
Pure input has browser compatibility issues

### ISSUE THREAD

**Issue by SaitoWu** [yahoo/pure#244]
Mac OS X 10.9

Firefox 25.01
![img1](http://d.pr/i/DRzI+)

Chrome Version 31.0.1650.57
![img2](http://d.pr/i/yPgd+)

With different sizes.

Characters in Firefox has been covered a little, and they are not in the middle of input.

**Comment by jamesalley** [comment]
Unfortunately the screenshots are missing now for some reason. Very little to go on here.
