### ISSUE TITLE
Choice of 767px media query collapse to 100% as default

### ISSUE THREAD

**Issue by sdmajor** [yahoo/pure#247]
I understand that through tooling we have the ability to change the media queries but the choice for the default to collapse to 100% at 767px is a little puzzling to me. 

I have a surface Pro 2 that I am doing my testing on, the text scales 87% at 767px, which when doing a side by side comparison of both widths non-collapsed 720px and 768px look almost identical.

Therefore I believe the default collapse to 100% should be at 719px not 767px.

See attached image for side by side comparison of 720px(left) vs 768px(right) of the purecss.io website
![purecss](https://f.cloud.github.com/assets/1106830/1627454/3418c10a-56f2-11e3-93e8-c68c787822ed.PNG)
.

**Comment by jamesalley** [comment]
Closing as it's impossible to optimize media queries, down to the pixel, for every possible device.
