### ISSUE TITLE
.pure-hidden-phone is over-ridden by more specific selectors

### ISSUE THREAD

**Issue by mfeif** [yahoo/pure#257]
I wanted to hide a menu item from phone, and it didn't work;

.pure-menu li

is turning .pure-hidden-phone back on by setting display to "inline-block".

I was tempted to put in !important, but that always makes me nervous... perhaps better to restructure things so that these hidden classes are applied last?

Thanks!

**Comment by jamesalley** [comment]
The [New Menu PR] (https://github.com/yahoo/pure/pull/424) does have significantly reduced specificity in the selectors; Tilo gave every element its own classname.
