### ISSUE TITLE
Grid renders incorrectly in IE10+ (display: -ms-flex-box)

### ISSUE THREAD

**Issue by juandopazo** [yahoo/pure#264]
Reported in the YUI repo: https://github.com/yui/yui3/issues/1510 by @drjayvee.

- - -

See this example of a default calendar rendering: http://jsfiddle.net/XhLTH/

In IE 10 and 11, the header doesn't cover the width of the calendar pane.

Disabling the following property makes it render fine:

```
.yui3-g { display: -ms-flex-box; }
```

Apparently, IE10+ doesn't need this property anymore. Since the property is in the `yui3-g` rule, I'm assuming calendar isn't the only module with a problem.

**Comment by silentworks** [comment]
This issue need to be fixed, I ran into this same issue recently.

**Comment by jamesalley** [comment]
I'm seeing the same behavior in Safari, but not in Firefox. I need to investigate further.

**Comment by jamesalley** [comment]
Hm. In the fiddle provided, would it not be acceptable to use `yui3-u-1-8`, `yui-u-3-4`, and `yui3-u-1-8` on the child elements of `yui3-g yui3-calendar-header`, instead of using just `yui3-u` on all three?

**Comment by jamesalley** [comment]
Alternatively, you could solve the problem this way: wrap the child elements of `yui3-g yui3-calendar-header` with a `<div class="pure-u-1">`.

I suggest this because, if you look at the documentation, such a construct is required:

All child elements of a grid must be units
Child elements contained within an element with a pure-g classname must be a grid unit with a pure-u or pure-u-* classname.

c.f. http://purecss.io/grids/#introduction-to-pure-grids

**Comment by lkraav** [comment]
Yes exactly, what @jamesalley said. There's consecutive yui3-g element levels which isn't supposed to work right in the first place. The fact that non-flexbox Firefox displays it OK, is accidental and would regress to a broken state as soon as Pure gets upgraded to full non-vendor flexbox and flexbox also becomes a standard part of Firefox arsenal.

**Comment by jamesalley** [comment]
Thanks Ikraav for seconding my opinion on this.

I'm certainly reluctant to change the grids model to use `display: block`. That would cause all kinds of grief.

**Comment by lkraav** [comment]
You shouldn't. Flexbox is the way of the future no matter what and getting rid of the inline-block letter-spacing, as awesome and well-working as it actually has been (+ taught me a whole bunch about grids in general, no longer a blind boostrap-dummy yey!), is only a good thing.
