### ISSUE TITLE
IE8 automatically switch to Compatibility View with Grids

### ISSUE THREAD

**Issue by okuryu** [yahoo/pure#268]
#### Background

I'm working for the problem on the example of YUI Calendar (see yui/yui3#1448). This strange problem looks like a bug in IE8, but I'm tryng to fix it somehow. First, I made a simple patch by specifying `X-UA-Compatible` with a `meta` element for this problem (see yui/yui3#1462).

This looks good in the short term, but I decided to examine a little more carefully if it can't resolve this problem inside the code of YUI.
#### Root of problem

Direct cause of this problem is due to importing Pure Grids into YUI at yui/yui3#1240. As far as my examine, it looks like this problem occurs in a state where the [main.css](https://github.com/yui/yui3/blob/master/src/common/docs/assets/css/main.css) of YUI and Pure Grids are colliding and performing the processing focus to a `a` element (the exapmple has a logic that auto focus to the element after simulating click event). Also, this problem actually doesn't occur in YUI 3.13.0, and doesn't occur if I changed the following CSS of Grids.

``` diff
diff --git a/src/cssgrids/css/cssgrids-base.css b/src/cssgrids/css/cssgrids-base.css
index b16d871..06b9a17 100644
--- a/src/cssgrids/css/cssgrids-base.css
+++ b/src/cssgrids/css/cssgrids-base.css
@@ -65,13 +65,4 @@ https://github.com/yui/pure/blob/master/LICENSE.md
     word-spacing: normal;
     vertical-align: top;
     text-rendering: auto;
-}
-
-/*
-Resets the font family back to the OS/browser's default sans-serif font,
-this the same font stack that Normalize.css sets for the `body`.
-*/
-
-.yui3-g [class *= "yui3-u"] {
-    font-family: sans-serif;
 }
```

I have tried to overwrite the `font-family` according as [Pure Girds guide](http://purecss.io/grids/#using-grids-with-custom-fonts), but had no effect.
#### Workaround

I found some way to avoid this problem by tweak `main.css` as follows.

**1: Remove font styles for `body`.**

``` diff
diff --git a/src/common/docs/assets/css/main.css b/src/common/docs/assets/css/main.css
index a65fa34..5401005 100644
--- a/src/common/docs/assets/css/main.css
+++ b/src/common/docs/assets/css/main.css
@@ -25,7 +25,6 @@ html {
 }

 body {
-    font: 14px/1.4 'PT Sans', 'DejaVu Sans', 'Bitstream Vera Sans', Verdana, sans-serif;
     margin: 0;
     padding: 0;
 }
```

This is a simple change, but it has wide impact for all pages at yuilibrary.com.

**2: Remove `:focus` pseudo-class.**

``` diff
diff --git a/src/common/docs/assets/css/main.css b/src/common/docs/assets/css/main.css
index a65fa34..ecd7901 100644
--- a/src/common/docs/assets/css/main.css
+++ b/src/common/docs/assets/css/main.css
@@ -97,7 +97,6 @@ hr {
     top: 0;
 }

-.jump:focus { left: 40%; }

 /* -- Paragraphs and paragraph-like blocks ---------------------------------- */
 p,
```

This also strange result, this problem doesn't occur when removed this line. IE8 supports `:focus` pseudo-class (see [MSDN](http://msdn.microsoft.com/en-us/library/ie/cc304080.aspx)), but my guess is IE8 has any bugs about pseudo-class.

For now, I think my first way that specifying `X-UA-Compatible` is easy and less impact way to avoid this problem, but I'd like to hear if someone has any solution for this.

/cc @lsmith

**Comment by redonkulus** [comment]
Please re-open if still an issue.
