### ISSUE TITLE
button.pure-button vs. a.pure-button width discrepency

### ISSUE THREAD

**Issue by joemaller** [yahoo/pure#271]
Hopefully I'm just doing something stupid, but I'm seeing a strange width discrepancy between native `<button>` buttons and `<a>` buttons. Both are classed with `pure-input-1`, inside a `pure-u-1` div. Result is the same on Chrome/Firefox and Safari.

![screen shot 2014-01-11 at 6 26 56 pm](https://f.cloud.github.com/assets/8320/1895156/006642f2-7b18-11e3-8d96-30c1a7855b97.png)

Here's the plunkr that screenshot comes from: http://plnkr.co/edit/Fp5ZRrP076O2h2Iv1dgc?p=preview

The code's been reduced to this:

``` html
<div id="container" class="pure-g">
  <div class="pure-u-1">
    <form action="" class="pure-form">
      <p>
        <a class="pure-button pure-button-primary pure-input-1"><code>&lt;a&gt;</code> button</a>
      </p>

      <p>
        <button class="pure-button pure-button-primary pure-input-1"><code>&lt;button&gt;</code> button</button>
      </p>
    </form>
  </div>
</div>
```

Any idea what's going on here?

**Comment by joemaller** [comment]
Signed the Yahoo! CLA, FWIW

**Comment by jamesalley** [comment]
I'm looking into this now. Thanks for your patience @joemaller.

**Comment by jamesalley** [comment]
I found the answer to this issue. Anchors are box-sizing: content-box by default. Buttons are box-sizing: border-box by default. I suspect this issue was not noticed by Tilo and Eric because they like to use `box-sizing: border-box` in all their projects.

I will consider adding box-sizing: border-box to the .pure-button class.

**Comment by jamesalley** [comment]
Yep. I think these things should be consistent, so I'm going to normalize pure-button class with box-sizing: border-box. This will be in 0.6 with a bunch of other little fixes which improve the way form elements lay out and align. For example, everything will be vertical-align: middle to reduce the effects of slight sizing differences between browsers.
