### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by RickHolmes** [yahoo/pure#281]
This is not a bug with purecss as such, but occurs with a commonly used method of using it for a grid.

It seems that the default Android browser has a rounding issue with display: border-box; (-webkit-border-box). With a pure-g-r, pure-u-1-4 would not fit four across. Changing the width from 25% to 24.9999% fixed the issue with no loss in actual widths. I haven't tested other grid variations, but it's probably the same for all.

Something to be aware of.

**Comment by jamesalley** [comment]
I've seen similar issues when using display: border-box in certain browsers, sometimes only at certain zoom levels. Border-box is still just a bit buggy at times, YMMV. It's less likely to occur if you're using content-box.
