### ISSUE TITLE
Some minor issues i found

### ISSUE THREAD

**Issue by hidegh** [yahoo/pure#301]
**RESETTING FONT**
.pure-g [class *= "pure-u"] is CSS3, 
why not use .pure-g [class|=pure] which is CSS2 compilant (note no " and no -u is accepted)

**NON-RESPONSIVE CSS**
IS there really a need to have separate file for non responsive CSS? .pure-g and .pure-g-r is the same, even font-resetting is the same. The only difference is the media selector for .pure-g-r. When I first saw the amount of CSS files of the sources/"binaries" from Github, it took me some time to get over it...

**FORMS LABEL SIZE**
.pure-form-aligned .pure-control-group label **has bigger priority** than .pure-form .pure-input-1-2.

also when using input-sizes, the inline-block &NBSP is not addressed.

That's all, **I really like this framework**. Flexible, easy to understand, even for someone who's new in CSS/Web design...

**Comment by jamesalley** [comment]
Closing as there is not a clear, single issue to pursue. Please open separate issues for anything that you feel still needs attention. Thanks!
