### ISSUE TITLE
Issue: Grid laying next to each other

### ISSUE THREAD

**Issue by josleow** [yahoo/pure#302]
Two grids (pure-u-1-2) staying inside pure-g should lay next to each other; only Firefox for most grids has different layout as Chrome and Safari. I have one grid at the last floating right. Had to cheat by using firefox hack to reduce width from 50% to 49%. In a long run, it might not be good. I would like to know if there is any other solution? Thanks

**Comment by jamesalley** [comment]
I've seen a couple examples where a particular zoom level caused grids to render wrong (one box would overflow from the edge of the grid to the next line) in Firefox/Win. I observed this happening at different zoom levels: in one instance, when zooming in a stop; in another, when zooming out two stops. No other browsers, including Mac Firefox, were affected. Reducing the pure-u-1-3 value from 33.3333% to 33.3%, or performing a similar tiny fractional reduction of width, solved the problem. But I don't want to compromise the correct math in Pure to accommodate an occasional render flub for a particular zoom level in a particular browser on a particular platform; it's an edge case. But if you're worried about it, try reducing the width of your pure-u-* units by a tiny amount.
