### ISSUE TITLE
form enhencements

### ISSUE THREAD

**Issue by mendrik** [yahoo/pure#307]
Would it be possible to add css styles for prettier checkboxes and radio buttons?
And one thing that is missing is having input fields with units |_______|$|. This could be also used for search inputs where the input field has a small magnifying glass on the left.

**Comment by jamesalley** [comment]
Hm. While https://github.com/yahoo/pure/issues/239 makes sense to me, I don't understand how this suggestion is the same as https://github.com/yahoo/pure/issues/239. I also don't understand how to define "prettier checkboxes and radio buttons." Can you be more specific as to what problem you're trying to solve and what improvements would be welcome? Finally, I don't understand what you mean by "input fields with units |_______|$|", or how that relates to search inputs.

I'm sorry it's taken so long to get a response. It's possible other contributors were similarly confused and didn't take the time to request clarification.
