### ISSUE TITLE
How to colapse a menu?

### ISSUE THREAD

**Issue by softwarerero** [yahoo/pure#313]
The menu at http://purecss.io is colapsed on a small screen but none of the menu examples at http://purecss.io/menus/ has this feature. How can a menu be colapsed?

**Comment by jamesalley** [comment]
@ironbyron the "new" menu will be available when we launch Pure 0.6. At the moment I'm going through Pure issues, but soon I'll finish up adapting the Pure-site to the new menu, a prerequisite for getting Pure 0.6 out.
