### ISSUE TITLE
Submit button on aligned form does not line up correctly

### ISSUE THREAD

**Issue by SimonSteinberger** [yahoo/pure#328]
Not sure if this is actualyl a bug, but it kind of looks like one. The pure-controls (e.g. submit button) does not line up correctly with the input fields above when using an aligned form. It's visible in your example in both Firefox and Chrome:

http://stage.purecss.io/forms/#aligned-form

Up to version 0.4.x the left side of the button was in line with the left side of all input fields.

Anyways: great work with the new release - awesome!!

**Comment by jamesalley** [comment]
I'm rolling this into the next release. Already committed to my new-menu PR.

**Comment by jamesalley** [comment]
Closing as already rolled into https://github.com/yahoo/pure/pull/424
