### ISSUE TITLE
pure-button-active 

### ISSUE THREAD

**Issue by fliiiix** [yahoo/pure#345]
I try to use pure v.0.5.0. 

And I have the problem, a pure-button-active don't look different on IE 8. 
I think it's because `box-shadow` is not supported.  

Did I miss anything or is it a bug?

```
.pure-button-active,.pure-button:active {box-shadow:0 0 0 1px rgba(0,0,0,.15) inset,0 0 6px rgba(0,0,0,.2) inset}
```

**Comment by jamesalley** [comment]
Rolling `border-color: #000\9` into the next release.
