### ISSUE TITLE
Some ideas/remarks/issues

### ISSUE THREAD

**Issue by cnicodeme** [yahoo/pure#35]
Great great great project!
This might be a great alternative to Bootstrap, I think I'm gonna try it for my next project!

Some ideas/remarks/issues :

* You should add a striped/active state for the button. It's very useful when the user submit the form and it's send through ajax, having the button animated (striped moving) is a great way to indicate the user that the actions is performing.
* UX prefers that the user clicks on the menu to show submenu (dropdowns) instead of hover. I know this requires a bit of Js (maybe not?) but I can guarantee you that most of the users will click on the menu to see the submenu (I did it ;))
* You should add a part about which icon you are using (either a menu in the left of the documentation or in a page), maybe also listing which icon you are using (I saw the spining wheel, great, what other animated icon are you using?)

This is awesome! Thanks a lot :)

**Comment by jamesalley** [comment]
Active striped button is a nice idea. As Eric noted, though, it's not common to all websites. Also, I can think of  many other interesting ways to indicate an action is executing in the background. So this is not something that needs to be codified and standardized in Pure.

Great suggestions though, resulting in some good changes. Closing the issue now, as we've already taken what action we will.
