### ISSUE TITLE
Drop support for IE7

### ISSUE THREAD

**Issue by ericf** [yahoo/pure#365]
I think it's time for us to drop support for IE7, Can I Use has its global usage share at **0.12%**.

Dropping support will mean pruning all of the IE7 cruft from Pure *and* from the tools.

**Comment by jamesalley** [comment]
I've already begun to drop IE7 support. We've upgraded to Normalize 3.x and I've removed old IE properties from buttons, forms, etc. Not yet from Grids though; I'll address that at a later date. Grids is sensitive and I want to refactor it carefully and over-test it.
