### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by cina2012** [yahoo/pure#37]
hi thanx for nice worked.
can you added RTL support  to this css framework?

**Comment by jamesalley** [comment]
I'm very familiar with RTL support and going forward it will always be a consideration. Given the comment by @mosid, I'll give Tilo's new Menu coming in 0.6 another look.

However, I'll close this issue as there is nothing more specific to address. Duly noted!

**Comment by Ghostavio** [comment]
I'm having a issue with this:
```css
.pure-g [class*=pure-u] { font-family: sans-serif; }
```

for some reason it's causing arabic not to render properly on windows on chrome

**Comment by hitautodestruct** [comment]
+1
