### ISSUE TITLE
YUI is going away - what does this mean for Pure?

### ISSUE THREAD

**Issue by grantmcconnaughey** [yahoo/pure#373]
Given [the announcement that development of YUI is ending](http://yahooeng.tumblr.com/post/96098168666/important-announcement-regarding-yui), I was wondering what this means for Pure.

Is this a good thing, meaning that focus will be spent on Pure? Or is this bad, meaning that Pure is also going away?

**Comment by jamesalley** [comment]
I also feel Pure has been neglected for a few months. I attribute this largely to Tilo's departure. The YPT team is staffing up, though, and I'm happy to be turning my attention to Pure this quarter.  There's quite a backlog of issues and PRs to go through. I am working to resolve them and to execute our 2015 roadmap.

I sympathize as well with those who have expressed a desire for a component library, replete with markup and JS, now that YUI has been deprecated. I don't yet have an answer to that question.

**Comment by jamesalley** [comment]
In closing, some more thoughts on a post-YUI world:

  * I, too, am realizing that, despite Pure's core mission, sometimes you just need JS. Dropdown menus in Pure is a great example; they really require JS for good accessibility and proper UI interaction. So, with the next release I'll be providing sample code for that. I've written it in such a way that you can take it and incorporate it into your own app, or drop it wholesale into a page and it will enable any pure dropdowns. (It will look for pure-menu-has-children items).

  * My approach is to write vanilla JS. I won't be picking a winner when it comes to JS libraries. If you're concerned about browser compatibility, and you should be, you can use the files as inspiration for a port to your favorite library, or you can polyfill. The Financial Times already offers a polyfill service; expect to hear more exciting news about this technique later in 2015.

**Comment by SimonSteinberger** [comment]
Just as an idea for the JS driven menus: In our projects we auto-detect touch devices:
if ('ontouchstart' in window) {... }

On those devices, our Pure dropdown menus open on click - while on mouse controlled devices, the menus open on hover. Our users love it, because when using a mouse, it's just more intuitive if menus open on hover. and it involves just a minimum of extra code ... just a thought :-)

**Comment by jamesalley** [comment]
@SimonSteinberger Thanks for the suggestion. Your comment inspired me to add in such functionality. Because overriding it would be difficult, and not everyone will want to expose submenus on hover, I decided to make it optional via a `pure-menu-allow-hover` class:

```
        <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
            <a href="#" id="menuLink1" class="pure-menu-link">More</a>
            <ul class="pure-menu-children">
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Autos</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Flickr</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Answers</a></li>
            </ul>
        </li>
```

**Comment by SimonSteinberger** [comment]
Excellent :+1:

**Comment by macguru2000** [comment]
Not to downplay your idea @SimonSteinberger, but some browser/device combos with a mouse (touchscreen laptops) will have 'ontouchstart' in the window object and a mouse. This means that you cannot, reliably, across all platforms, determine if a user has a mouse or not by that property alone. 

Just some food fort thought. Cheers! :)
