### ISSUE TITLE
Main site (docs; grid?) broken

### ISSUE THREAD

**Issue by sgserg** [yahoo/pure#375]
Using latest iOS stock browser. Switching device orientation a couple of times makes the page horizontally scrollable.

**Comment by jamesalley** [comment]
@pR0Ps You're right. Thanks for that tip. Should make it much easier to fix. Now that I can more easily inspect what's going on, I can see it has nothing to do with grids. It has to do with the layout and the .active class. In other words, this is a problem specific to the pure-site and its custom layout, not a problem with the core of Pure.css itself, and certainly not with grids.

**Comment by jamesalley** [comment]
Closing as I have an open issue in pure-site to address this, assigned to me.
