### ISSUE TITLE
Grids specify a font-family: why?

### ISSUE THREAD

**Issue by jconniff** [yahoo/pure#379]
I noticed another thing I have to override in Pure, that seems opinionated.
I can't think of a reason for this.

.pure-g [class *="pure-u"] {
font-family: sans-serif;
}
Suppose I specifically choose a font-family for my site with
body {
font-family: fontOfMyChoice;
} 
anywhere I use grids, I'll see 'san-serif' instead of my font.

**Comment by lkraav** [comment]
@redonkulus https://caniuse.com/#feat=flexbox shows ~95% usage. Wdyt, should the docs update the recommendation to `.pure-g [class *= "pure-u"] { font-family: inherit; }`?

AFAIU this font stack was necessary in the earlier days where `inline-block` model might have been the prevalent display model, but now it just mostly gets in the way, having to override things lower in the element stack.

Maybe even combine an updated recommendation w/ `@supports {}`.

Your thoughts?

**Comment by KeiroD** [comment]
Hmm. I think this would be a good change, as reducing weird constructs would be good, in my book.

I'd go with this change. personally.

**Comment by lkraav** [comment]
@redonkulus your thoughts on re-open?

**Comment by redonkulus** [comment]
@lkraav will this break anyone if we change it?

**Comment by lkraav** [comment]
> will this break anyone if we change it?

Ain't that the million-dollar question :)

Release 2.0.0 and call it "maybe backwards-compatible"?

**Comment by septatrix** [comment]
I also just stumbled upon this. Based on the discussion it seems to me like a remnant of more complicated times.

Is the font override still on track for being removed?

**Comment by redonkulus** [comment]
@lkraav we already did a major version bump so I guess that ship has sailed.

@septatrix I'm ok with removing the font family, it's not really needed anymore since flexbox and grid are available everywhere. Anyone that wanted it changed already would have done it in their project.

**Comment by septatrix** [comment]
> @septatrix I'm ok with removing the font family, it's not really needed anymore since flexbox and grid are available everywhere. Anyone that wanted it changed already would have done it in their project.

Should I create a PR then or would you like to do it? I assume the codebase is simple enough for me to find it :D

**Comment by redonkulus** [comment]
yes please do!

**Comment by septatrix** [comment]
Any advantage of using `inherit` instead of just removing the `font-family` declaration?

**Comment by septatrix** [comment]
Looking into the source it seems like the hack is still used for IE10/IE11 which are still supported.

https://github.com/pure-css/pure/blob/master/src/grids/css/grids-core.css#L33-L38

They theoretically support flexbox but they seem to suffer from a few potential issues, see the respective tab in caniuse: https://caniuse.com/flexbox

So while in my opinion no one today should go out of their way to support these browsers as they are officially unsupported as of this year (yay!) I am not sure if this should be done without a major version increase...

**Comment by redonkulus** [comment]
Good point about the IE 10/11 support. We can just remove support for those browsers since they are EOL'd and release 3.x.
