### ISSUE TITLE
Add dependency version checking badge

### ISSUE THREAD

**Issue by paazmaya** [yahoo/pure#386]
Such as Gemnasium offers.
Current state looks like:
https://gemnasium.com/paazmaya/pure

**Comment by jamesalley** [comment]
Noted. It's not such a big deal though. Only contributors to Pure who want to build from source should worry about these dependencies. Most end-users will pull from the CDN. Also, look at the dependencies which are out of date according to the second [URL you provided] (https://david-dm.org/yahoo/pure#info=devDependencies&view=table). They are all using carets. So a dependency listed as ^0.2.0 in Pure's codebase will automatically pull in the latest minor version, thus pulling in the current stable 0.3.1. You wouldn't really be out of date at all.
