### ISSUE TITLE
Sticky footer in template

### ISSUE THREAD

**Issue by 4goodapp** [yahoo/pure#387]
I Downloaded your Template example http://purecss.io/layouts/marketing/ but the footer is not sticky. do you have other layout template where with a sticky footer

**Comment by jamesalley** [comment]
That is trivial to implement on top of Pure with position: fixed or position: absolute. 

e.g., 

```.footer {
  position: fixed;
  bottom: 0;
  width: 100%;
}```

Sorry it took so long to get back to you about this question.
