### ISSUE TITLE
Pure examples have wrong url

### ISSUE THREAD

**Issue by abdelouahabb** [yahoo/pure#397]
hi,
the example have bad url, i dont know if it is done by purpose to push the user  to do something :p

for example `http://yui.yahooapis.com/pure//pure.css`

**Comment by jamesalley** [comment]
@abdelouahabb, thank you for bringing this to our attention. However, I'm not sure what action I can take without more information. I gripped through all the code of pure-site and could not find such a URL.

Issues related to the Pure site may be filed at http://github.com/yahoo/pure-site/issues/

**Comment by abdelouahabb** [comment]
you are welcome, and thank you for the framework.
