### ISSUE TITLE
transition from small forms to large forms not the same as small grids

### ISSUE THREAD

**Issue by skybrian** [yahoo/pure#401]
I noticed that the forms switch to a wider version at 480px (removing a margin above a button, for example), but "small" grids start working at 568px. As a result, if you use grids and forms together then there are two transitions to think about.

I'm new at responsive CSS, but perhaps the form media query should match the grid media query so that there is only one transition without a gap in between?

**Comment by jamesalley** [comment]
This is a great point. The 480px breakpoint is obviously a nod to iPhone in portrait orientation. I'm not sure how the 568px value was chosen. At any rate, the values are arbitrary and easily customized. As such I'm closing this issue, but I'm adding this point of consideration to my personal notes. Thanks for the suggestion.
