### ISSUE TITLE
Grid not work in Chrome?

### ISSUE THREAD

**Issue by sokvanrithy** [yahoo/pure#403]
I am only using Base and Grid. Here's my page source code: http://pastebin.com/Sk3YzZs8

The grid is working fine with my Firefox 32 & IE 11. The content on the left and side on the right.
But, in my Chrome 38, the side is just not on the right but bottom of the content on the left.
What could be the issue with that? Thanks!

P.S:
- In Mozilla Firefox (v.33), Internet Explorer (v.11) & Safari (v.5) the grids are just working fine in every pages.
- But, in Chrome (v.38) & Opera (v.25) the grid is not working in frontpage. Yet, others page which are using the same grid class are showing good. They're having the same grid class (in front-page and other pages). (that's weird)

Firefox
![firefox](https://cloud.githubusercontent.com/assets/4959325/5082184/8f77e65e-6f0e-11e4-9b61-7baebac0a783.jpg)

Chrome
![chrome](https://cloud.githubusercontent.com/assets/4959325/5082185/902e5d30-6f0e-11e4-8e7b-a8768145f0fe.jpg)

**Comment by jamesalley** [comment]
@sokvanrithy, I took your pastebin code, and it worked fine for me in Chrome Version 39.0.2171.95 (64-bit). Are you still having issues? Please reopen if so.
