### ISSUE TITLE
Multi-column form not working when base.css used

### ISSUE THREAD

**Issue by alex-barylski** [yahoo/pure#404]
Not sure if this is a bug or I am not understanding something.

I am trying to build a multiple column form (using your example) but instead of the rollups I am using:

base-min.css
grids-responsive-min.css

Here is my code:

<html ang="en" class="js">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <link type="text/css" rel="stylesheet" href="css/base-min.css" media="all">
    <link type="text/css" rel="stylesheet" href="css/grids-responsive-min.css" media="all">
    
  </head>
  <body >
    
    <section class="content orange">
      <div class="pure-g slimdown">
        <div class="pure-u-1-1">
          <form class="pure-form pure-form-stacked" action="contact" method="post" id="quoter-contact-form" accept-charset="UTF-8">
            <div class="pure-g">

              <div class="pure-u-1 pure-u-md-1-3">
                <input placeholder="---" style="text-align: center;" type="text" name="phone_areacode" value="" maxlength="3" class="form-text required">
              </div>
              <div class="pure-u-1 pure-u-md-1-3">
                <input placeholder="---" style="text-align: center;" type="text" name="phone_prefix" value="" maxlength="3" class="form-text required">
              </div>
              <div class="pure-u-1 pure-u-md-1-3">
                <input placeholder="----" style="text-align: center;" type="text" name="phone_suffix" value="" maxlength="4" class="form-text required">
              </div>
            </div>
          </form>
          
        </div>
      </div>
      
    </section>
    
  </body>
</html>

If you change the base-min to pure-min the fields align as expected...what am I missing here??? I have tried including every single CSS module listed here:

http://purecss.io/customize/#individual-modules

Still happens...do I need to build the CSS myself using SASS?

Alex

**Comment by jamesalley** [comment]
@alex, the project does not use SASS. Regardless, you shouldn't need to do a build unless you want to customize the breakpoints for responsive grids (in other words, which widths trigger sm, md, lg, and xl styles). 

I'm looking into your particular problem more closely now.

**Comment by jamesalley** [comment]
@alex-barylski, you're missing the grids CSS file; you need it in addition to the grids-responsive file. That file is included in pure.css so that's why using pure-min instead of base-min helped you.
