### ISSUE TITLE
Rendering delays when changing the hidden attribute in IE8

### ISSUE THREAD

**Issue by macguru2000** [yahoo/pure#405]
I have a single page web application that uses pure.css, in the application I show and hide different panels (divs) by toggling the hidden attribute using javascript. This seems to work fine in most browsers, but there is an extremely annoying rendering delay when I do this in Internet Explorer 8.

Here is a simple proof that you can run in IE8 to experience the behavior I am seeing. Any workarounds or ideas on how to fix this would be amazing.

```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Pure.css - Toggle Hidden Elements Test</title>

    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <style type="text/css">
        .panel {
            max-width: 400px;
            margin: 2em 0;
            padding: 2em;
            border: 1px gray solid;
            background: #ededed;
        }
    </style>
</head>

<body>
    <h2>Pure.css - Toggle Hidden Elements Test</h2>
    <p>
        In this test, the panel visibility toggle fails to render immediately
        in <abbr title="Internet Explorer 8">IE8</abbr>.<br>It seems to take
        some arbitrary amount of time for the document to update.<br>Sometimes
        moving the mouse seems to help the document update faster.
    </p>
    <p><br></p>
    <p><br></p>

    <div>
        <button id="toggle-button" class="pure-button">
            Toggle panel visibility
        </button>

        <div id="panel1" class="panel">
            <h1>I am panel 1</h1>
            <p>
                You will see me when the page loads and if you click the toggle 
                button when Panel 2 is visible.
            </p>
        </div>

        <div id="panel2" class="panel" hidden>
            <h1>I am panel 2</h1>
            <p>
                You will see me if you click the toggle button when Panel 1 is
                visible
            </p>
        </div>
    </div>

    <script type="text/javascript">
        // store references to the panel dom elements
        var p1 = document.getElementById('panel1');
        var p2 = document.getElementById('panel2');

        // bind an event listener to #toggle-button which will toggle the 
        // panels visibility
        document.getElementById('toggle-button').onclick = function(event) {
            if (p1.getAttribute('hidden')) {
                p1.removeAttribute('hidden');
                p2.setAttribute('hidden', true);
            } else {
                p1.setAttribute('hidden', true);
                p2.removeAttribute('hidden');
            }
        };
    </script>
</body>
</html>
```

**Comment by macguru2000** [comment]
Thanks for the input @peterblazejewicz, though there are some differences with your assertions and my problem. Firstly, I am not using a shim library, notice in the proof I posted above that the only thing imported is Pure.css. Also, the `hidden` attribute does work for the most part in IE8 standards mode. I assume this is because Pure.css has rules that use the CSS class `[hidden]` to emulate the new auto hiding HTML5 behavior.

Interesting enough, it works fine until you add or remove the `hidden` attribute with Javascript, when that happens the rendering update is seriously delayed. I also used vanilla Javascript in the example to show that the problem isn't related to another library or framework. This could very well be a bug in IE8's rendering engine.

Also, just to be clear, a custom class for hiding elements would work, but I was hoping to use the newer HTML5 `hidden` approach.

**Comment by jamesalley** [comment]
Sorry for the delay when apparently this was a pressing issue.

Funnily, the JSFiddle won't run in IE8. But I believe you that IE8 is slow. IE6-8 browsers are all pretty poor performers when it comes to JavaScript. Almost anything involving JavaScript will appear noticeably slower.

I agree with @peterblazejewicz that instead of swapping the attribute try swapping a CSS classname. Just to try. There might be some quirk to IE whereby the different approach yields different results.

Another thing you could try is not creating a function every time the user clicks. There is overhead in JS to creating new objects. Generally it's only presents itself as a big problem when you're creating lots and lots of objects. But still, it's overhead, and IE is slow. Try this instead:

```
var switchEm = function (event) {
    if (p1.getAttribute('hidden')) {
        p1.removeAttribute('hidden');
        p2.setAttribute('hidden', true);
    } else {
        p1.setAttribute('hidden', true);
        p2.removeAttribute('hidden');
    }
}

document.getElementById('toggle-button').onclick = switchEm;
```

That way you're only creating the function once, and it's already created before the click even happens. The way you wrote it originally, you're creating the function and executing it after each click. That may be part of the delay you experience in IE.

Closing as this is not really related to Pure itself. Good luck!

**Comment by macguru2000** [comment]
Thanks for taking the time to look at this @jamesalley, you are completely right the root cause of this problem is not related to pure.css, but it is still unfortunate and a bit upsetting when part of the core functionality (hiding elements) doesn't work correctly in what is documented as a supported browser. Toggling hidden elements seems to me to be the main reason to use `hidden` anyways, otherwise why even put the DOM content into the page at all, right?

That said, there is a good workaround, you and @peterblazejewicz both mentioned it. Still, as a developer who was brand new to pure.css, I feel bummed. I would of at least liked to see a documented warnings about using the hidden attribute in IE8 and probably IE7 too. Looks like the `.hidden` class will still be in my repertoire for a while :)

ps, I updated the fiddle by replacing pure.css with just a simple `[hidden]` css rule and it uses the more efficient Javascript, we'll see if that fixes it.
