### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by andrerom** [yahoo/pure#406]
Bower package of this project is outdated and points to the old `yui/pure` repo, this causes [issues](https://github.com/Bee-Lab/bowerphp/issues/54) for other third party implementations of bower.

Besides would be nice with new release.

**Comment by jamesalley** [comment]
@neon5, we are not guaranteeing backwards compatibility with previous releases until we get to 1.x state. That said, I don't expect you to have trouble switching from 0.5 to 0.6 unless you use Paginator, which is being removed in 0.6, or Menu, which has been significantly revised.

If you use Paginator, you can copy the styles from 0.5 or roll your own variant; they're just inlined button-style links. If you use Menu, you'll have to add more CSS classnames to your HTML and do some QA.

There's also no reason why you couldn't continue to use 0.5 if you use that as the foundation of your project. You wouldn't have to "upgrade" if you didn't want to; you could wait for 1.0 to come out before switching.

**Comment by jamesalley** [comment]
Closing, as the release is coming this quarter per our 2015 roadmap.

**Comment by neon5** [comment]
@jamesalley, I appreciate the reply.  I am using the current version in a small project and it's working out great.  I look forward to using the next version in my upcoming larger project.

Thank you.
