### ISSUE TITLE
Input type "file" not handles as other input types are

### ISSUE THREAD

**Issue by ctron** [yahoo/pure#407]
The input type "file" is not handled, styled as the other input elements. This breaks the form layout.

**Comment by jamesalley** [comment]
Historically, input[type="file"] has been notorious for its clunkiness, inability to be styled much, and disparities between browsers. I wouldn't be surprised if it's more complicated than the solution you propose, but I'll make a note of this as something that should be periodically examined as an area for potential improvement. I'm leaving this issue open as a result.

**Comment by ctron** [comment]
Well this is true, but is it more about the fact that the whole form layout is broken and less about the styling of the element itself.

**Comment by jamesalley** [comment]
@ctron, I just took a closer look at this issue, in the process whipping up [this fiddle] (http://jsfiddle.net/james_alley/wff78oyy/). I don't see any problem; in fact, your suggested missing definition causes problems. So I'll need to see the context before I can decide how to proceed. Can you provide a fiddle or other example illustrating the problem? It's possible that the solution you propose is fine for your use-case, but does not warrant inclusion in Pure.

**Comment by ctron** [comment]
I just created two screenshots:

Actual:
![actual](https://cloud.githubusercontent.com/assets/202474/5717749/3995e5aa-9b06-11e4-9e82-ac2bef3aaf16.png)

Expected:
![expected](https://cloud.githubusercontent.com/assets/202474/5717751/3df36fa0-9b06-11e4-9310-526065567597.png)

While testing with the sample form from the pure web page, I also found out that this only happens when the file element is before the button. If the file input element is, for example, after the password, then it works as expected.

I will try to create a fiddle myself, never did that before ;-) So give me a few minutes. But in the meantime I created [a gist](https://gist.github.com/ctron/c9ba458755e85ed16bf2).

**Comment by ctron** [comment]
I guess I updated your fiddle. Maybe you can check. Thanks!

**Comment by jamesalley** [comment]
OK, I see what you mean now. I will add

`.pure-form-stacked input[type="file"],`
to the next release

**Comment by jamesalley** [comment]
Done. Thanks for this suggestion!

**Comment by jamesalley** [comment]
https://github.com/yahoo/pure/blob/master/src/forms/css/forms.css#L189
