### ISSUE TITLE
WARN during `npm install` about deflate-crc32-stream@0.1.2 deprecation

### ISSUE THREAD

**Issue by peterblazejewicz** [yahoo/pure#416]
When installing **Pure** deps via `npm install` following is shown in console:
```
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
```
This is probably due to outdated NPM package/module dependency used in project. Will do PR

**Comment by jamesalley** [comment]
Thanks for the commit, I'll close this issue and let the PR take it from here.
