### ISSUE TITLE
Unified, single way to handle user focus on UI elements

### ISSUE THREAD

**Issue by peterblazejewicz** [yahoo/pure#418]
At the moment Pure appears to have no single model for showing user elements focus. Some elements got outline handling back:
https://github.com/yahoo/pure/pull/63
but other elements have no outlines. It would be nice to have single model of handling user focus in Pure, similar to single model applied for example by Bootstrap

**Comment by jamesalley** [comment]
I have been considering this and closely examining Pure and Bootstrap.

While the outline property has been set to 0 for many form elements in Pure, those same elements gain a border color on focus, so accessibility is not sacrificed.  

In Bootstrap, I see they are doing similar for form inputs. I don't see a "single model" in Bootstrap. Checkboxes and radio buttons, for instance, have outlines;  text inputs have a .form-control:focus {outline: none} rule applied.

So, I'm not sure exactly what change you're proposing, given that the example to which you refer (Bootstrap) doesn't seem to shed light on the problem. Feel free to re-open with more detail, or to submit a PR with your proposed changes.

**Comment by peterblazejewicz** [comment]
@jamesalley 
Let me explain: which of below buttons (or anchors styled as buttons) - that is actionable user elements) has actually focus on below screenshots? Pure/Bootstrap/Foundation

![20150105225738](https://cloud.githubusercontent.com/assets/14539/5620694/70baaeea-952e-11e4-8f6c-d811a49b6350.jpg)

![20150105225517](https://cloud.githubusercontent.com/assets/14539/5620696/7bcc5694-952e-11e4-92c8-51f65627c329.jpg)

![20150105225459](https://cloud.githubusercontent.com/assets/14539/5620697/7bd24482-952e-11e4-9c05-09b274cd8711.jpg)

![20150105225611](https://cloud.githubusercontent.com/assets/14539/5620702/86383a1c-952e-11e4-9af5-7b2ec202133e.jpg)

![20150105230039](https://cloud.githubusercontent.com/assets/14539/5620721/bb616330-952e-11e4-936e-0418bd0f2a1d.jpg)

![20150105230319](https://cloud.githubusercontent.com/assets/14539/5620758/231c20d2-952f-11e4-9a27-4dd4b766025e.jpg)

![20150105230303](https://cloud.githubusercontent.com/assets/14539/5620759/231f3cae-952f-11e4-81d5-0079b5084177.jpg)

![20150105230247](https://cloud.githubusercontent.com/assets/14539/5620760/23235460-952f-11e4-9c97-2f7ff2c1eb7c.jpg)
