### ISSUE TITLE
repo removed from Google search

### ISSUE THREAD

**Issue by gdi2290** [yahoo/pure#420]
https://www.chillingeffects.org/notices/10275257#infringing_url_598767483

**Comment by jlecomte** [comment]
The work that is *supposedly* infringing on a copyright is a movie, according to the complaint. However, there are no movies on the following pages:

https://github.com/yahoo/pure/releases/
https://github.com/yahoo/pure 

Also, the site claiming infringement is a, hum, porn site. This is a bogus complaint. How do we address this?

**Comment by gdi2290** [comment]
yeah it's the DMCA takedown
https://support.google.com/legal/contact/lr_counternotice?product=websearch

**Comment by jlecomte** [comment]
Thanks. I filed a counter notification. That should hopefully take care of it.

**Comment by thaJeztah** [comment]
> Also, the site claiming infringement is, hum, a porn site.

Well, that confirms this is a sexy project! :smile:
