### ISSUE TITLE
CLA rescanning

### ISSUE THREAD

**Issue by chaoaretasty** [yahoo/pure#421]
I submitted a PR regarding flexbox (yahoo/pure#419) but hadn't signed the CLA. I've since signed it but the bot hasn't tried to revalidate it and still has it marked as a failing PR.

**Comment by okuryu** [comment]
Yes, it's @yahoocla's issue not Pure. I'm not sure appropriate repo.

**Comment by chaoaretasty** [comment]
Ok thanks. I assumed that the Pure repo owners had a way to force a retest or something.
