### ISSUE TITLE
Horizontal Menu Issue

### ISSUE THREAD

**Issue by joeymbryan** [yahoo/pure#422]
I'm having an odd issue where items in a horizontal menu will not always load.

We use mostly chrome but we've been experiencing this issue on every browser we've used. Oddly, it seems to happen much more frequently on mac's.

These menu's have sub-menus and in some cases sub-sub-menus.

It seems to consistently be the last 1 - 3 items of a 4-6 item menu which don't load.

Upon, refresh they always load completely.

I've been looking around and haven't been able to find anyone else with a similar problem.

Thanks, Joey

**Comment by lawsonry** [comment]
Are you getting any console errors? When you open the developer pane, do you see any css problems in the menu elements?

**Comment by jamesalley** [comment]
@joeymbryan, can you provide a URL or a JSFiddle illustrating the problem? I'm not sure what you mean by "not always load." Pure has nothing to do with markup rendering or loading of dependencies. Still, I'd like to help you diagnose your problem.

**Comment by joeymbryan** [comment]
@lawsonry  and @jamesalley thanks for getting back to me. We are currently using the menu found here http://purecss.io/menus/#add-dropdowns-to-menus

If we look at the purecss site example I linked, it would be as if "Finance or Other" don't complete rendering and thus don't show up.

I don't receive any console errors and when I refresh the page, the menu renders completely.

I can't provide a link currently, I was trying to find out if this was a problem you've occurred in the past or if you knew of any possible render issues.

**Comment by jamesalley** [comment]
Hm. That symptom is impossible to diagnose without seeing an example. Sounds like you've got some box width issues on parent elements.

Another thing I can't understand is why reloading would help. Why would it render on reload, but not on the initial load? Are you building your menu on the fly?

As an aside, I'd like to point out that Pure 0.6 will be dropping this Menu construct soon, and with it, support for these types of nested menus will disappear. The new Menu supports CSS-only drop-down menus, but with only one level of nesting. This will likely not fit in at all with your menu system, so be prepared to grab some of the old menu code from Pure 0.5 to incorporate into your own CSS if you wish to keep your menus the same. You'll hear more about this in the coming weeks. Ultimately, menus are too opinionated to belong in Pure, at least not in the pure-min rollup.
