### ISSUE TITLE
cdn should have a 'latest' option

### ISSUE THREAD

**Issue by olsonpm** [yahoo/pure#426]
I'm building a node project generator tool and it would be awesome if I could point to the 'latest' version of yahoo pure without updating my tool every time you guys bump a version.  I searched a bit and couldn't find a cdn that offered a 'latest' option, so if there is one please let me know.

**Comment by jimaek** [comment]
There is //cdn.jsdelivr.net/pure/latest/pure-min.css if you want

**Comment by olsonpm** [comment]
Thanks much

**Comment by jamesalley** [comment]
Thanks for the link, jimaek. 

FYI, this sounds like a dangerous thing to do. The next version of Pure, 0.6, which I am working hard to release, will not be fully backwards compatible with the previous version. In particular, Menu will change quite a bit. While it will be easy to update your Menu markup to suit, and Menu will overall be much easier to customize, anyone using a "latest" Pure coupled with Menu would suffer breakage.

**Comment by jimaek** [comment]
Yes, we do not encourage using `/latest/` in production but @olsonpm mentioned that its for a generator so I assumed it will be safe.

We also offer aliased versions such as
`//cdn.jsdelivr.net/pure/0.5/pure-min.css` for the latest 0.5.x version
`//cdn.jsdelivr.net/pure/0/pure-min.css` for the latest 0.x version
[Documentation](https://github.com/jsdelivr/jsdelivr/#version-aliasing)
