### ISSUE TITLE
radio button group

### ISSUE THREAD

**Issue by daveed80** [yahoo/pure#427]
I apologize in advance if this is provided out of the box...

Does the current css provide a manner in which to create a yes/no radio button group, with a field label to indicate what the options are for?

ex.) 
        Is this provided ?  (label)
          - Yes                (radio)
          - No                  (radio)

**Comment by jamesalley** [comment]
Does this answer your question? http://purecss.io/forms/#checkboxes-and-radios

**Comment by jamesalley** [comment]
Here's a fiddle with a little more detail:

http://jsfiddle.net/james_alley/gu80a3kq/

**Comment by daveed80** [comment]
That's excellent!

Thanks very much for your help and time!

**Comment by daveed80** [comment]
I initially tried utilizing the field set however I'm ultimately trying to incorporate this into the "pure-form pure-form-aligned" format.

ex.)

**Comment by daveed80** [comment]
I initially tried utilizing the field set however I'm ultimately trying to incorporate this into the "pure-form pure-form-aligned" format in one form.

something like...

<div class='pure-control-group'>
	<label for='firstname'>First Name</label>
	<input id='firstname' type='text'>
</div>

<div class='pure-control-group'>
	<label for='lastname'>Last Name</label>
	<input id='lastname' type='text'>
</div>

<div class='pure-control-group'>  ???
   Name Provided : Yes <input type='radio'>No<input type='radio'>
</div>
