### ISSUE TITLE
Where are the grids 

### ISSUE THREAD

**Issue by gautamz07** [yahoo/pure#428]
Well Thanks for this nice lightweight framework , but i looked in the grid.css file and could't find any code , basically i am interested in the code that makes these Magical Grids HAppen and also the code that makes these magical grids responsive , it will be really helpful if someone can point me as to exactly where these files are . 

Thanks

**Comment by jamesalley** [comment]
https://github.com/yahoo/pure/tree/master/src/grids

Per the ReadMe: The unit style rules are generated via Pure's rework-pure-grids Rework plugin.

Try checkout out the Pure repo and running Grunt. You'll see that a /build folder is generated, and in it there will be a bunch of grids files.

**Comment by gautamz07** [comment]
Thank you.
