### ISSUE TITLE
Little menu-collapsing display bug - horizontal scrollbar (Firefox on desktop)

### ISSUE THREAD

**Issue by robertlagrant** [yahoo/pure#430]
1) Go to http://purecss.io/
2) In Firefox (Windows 7), resize the window horizontally until the left menu changes to a hamburger
3) Open the hamburger to see the menu
4) Hit the maximise button in Firefox

Voila! Your content now flows out of the right hand side of the screen, even though your menu is back to normal! To fix it, repeat 2->4, but collapsing the menu back to a hamburger in step 3.

**Comment by jamesalley** [comment]
This is a known issue and I've fixed it. New release imminent!

**Comment by robertlagrant** [comment]
Oh sorry, brand new to Pure. Thanks!
