### ISSUE TITLE
P in MAIN breaks Grid in IE11

### ISSUE THREAD

**Issue by snowlep** [yahoo/pure#434]
Hello, I've come across an issue using Pure Grids. I've isolated it down to having a `p` inside a `main` element that is a unit class inside a grid class breaking the grid in IE 11. In Chrome it appears as expected, and changing the `main` to a `div` fixes the problem in IE 11. Also, removing the `p` gets rid of the problem. Any thoughts?
```html
<div class="pure-g">
<div class="pure-u-1 pure-u-md-2-3" style="background:purple;">
<p> a paragraph
</div>
<div class="pure-u-1 pure-u-md-1-3" style="background:orange;">
1 third
</div>
</div>

<div class="pure-g">
<main class="pure-u-1 pure-u-md-2-3" style="background:purple;">
<p> a paragraph
</main>
<div class="pure-u-1 pure-u-md-1-3" style="background:orange;">
1 third
</div>
</div>
```

**Comment by jamesalley** [comment]
Closing your paragraph with a `</p>` also solves the problem. That would be my recommended solution.

**Comment by jamesalley** [comment]
c.f. http://jsfiddle.net/james_alley/wjLahy4z/2/

**Comment by jamesalley** [comment]
Also note that IE11 does not support `<main>`. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

**Comment by jamesalley** [comment]
Closing as this is not a problem with the grid system per se.
