### ISSUE TITLE
equivalent grid sizes 1-6 and 4-24, but not 1-3 and 4-12?

### ISSUE THREAD

**Issue by stevenvachon** [yahoo/pure#435]
There is no 4-12.

**Comment by jamesalley** [comment]
That's correct. I just reviewed all the units and only the 24ths increment one-by-one like that. All the others, presumably, are easy enough to grok. Adding synonyms for all those units would add unnecessary weight to Pure.

**Comment by jamesalley** [comment]
I suppose this could be a pain if you're writing out your grid unit classes programmatically, incrementing as you go, and you wanted a 12-column grid; but even then you would have the option of using a 24ths grid, and you would just increment by two.

**Comment by stevenvachon** [comment]
But 24ths is a bit too granular for what I'm doing and 12ths would be better, but some are missing.

**Comment by jamesalley** [comment]
But there will be no difference. Incrementing by 2 (2/24, 4/24, 6/24) will give you the equivalent of using a 12-column grid, if you're generating the classes programmatically.

If you're writing the classes by hand, it should be easy enough to convert 2/12 to 1/6, 3/12 to ¼, 4/12 to ⅓, etc. right in your head. It's just not worth the k-weight penalty to add more synonyms to the grid units.

**Comment by stevenvachon** [comment]
```html
<div class="pure-u-1-6"/>
<div class="pure-u-1-3"/>
<div class="pure-u-1-4"/>
<div class="pure-u-15-24"/>
```
I don't come from an Imperial mathematics system, so the above is far from clear.

But, I understand what you're saying, and I'd already switched to 24ths. Even if they're a bit too granular, they at least add up without using multiplication.
