### ISSUE TITLE
Grids in Firefox not filling height

### ISSUE THREAD

**Issue by CaitlinWeb** [yahoo/pure#436]
![pure-grid-issue](https://cloud.githubusercontent.com/assets/6975769/6134298/3ea635ca-b12e-11e4-8d35-697fe54de6f8.png)

As you can see in the screenshot above, the grid works great in Chrome. When I went to test it in Firefox (version 34), I discovered that the heights weren't matching.

The above screenshot is the website grid at http://purecss.io/start/ with the contents of the indicated cell removed, the top being Chrome and the bottom Firefox. It may be faint, but you can see that the border doesn't go all the way to the bottom in Firefox.

The fix for this is adding `display: flex` to `.pure-g`. Also it looks fugly without `flex-flow: row wrap` added, too.

**Comment by jamesalley** [comment]
I'll get a second opinion on this, but I think the answer is: generally you don't want to apply styling (like borders) to your grid classes. Here, there is a custom border on the grid, so you can see what's going on. But generally, you should use your grid for transparent layout, not for decoration. Put borders on the elements within your grid, if you need them. Or use pure-table if you want to organize and delineate data with borders.

@ericf @tilomitra Further thoughts...?

**Comment by jamesalley** [comment]
Also, see http://purecss.io/grids/#applying-padding-and-borders-to-grid-units in the documentation for Grids. There you'll see that we recommend applying borders to child elements of grid units, not to grid units themselves.

**Comment by ericf** [comment]
@CaitlinWeb what @jamesalley is saying about no borders on grid units is the recommendation.

@jamesalley it's probably time to go back over all Grids flexbox rules to make sure they're up to date with what browsers support. We intentionally used an opt-in approach to pushing only the browsers we knew worked correctly to the flexbox based grids. If Firefox is not being opted-in, we should see why and if it can be.

**Comment by jamesalley** [comment]
Yes. A review of Grids is on the 2015 Pure Roadmap. FF in particular has some bugs with Grids when zooming. I'll leave this issue open, as this is something I should try to address if possible.

**Comment by lkraav** [comment]
The issue title should definitely be adjusted to express a narrower scope. This is specific to having visibility an empty grid-unit while having it bordered.

But overall, flexbox is the way of the future anyway. I think the only concern here is how to make the transition from inline-block as painless as possible. http://caniuse.com/#search=flex shows FF has been OK with flex since a while back already. But Android browser is probably the main issue.
