### ISSUE TITLE
Side menu responsive issues

### ISSUE THREAD

**Issue by MattGreyDesign** [yahoo/pure#438]
When testing the responsiveness of the side menu (http://purecss.io/layouts/side-menu/) I noticed that when opening the menu using the hamburger button at smaller (tablet and desktop breakpoints) page widths and then resizing to full desktop width caused the layout to break where the grid still compensates for the open menu.

### Desktop
http://i.imgur.com/r4iBb5U.jpg

### Small width (after opening menu)
Note that the page also scrolls around behind the menu here, which is not usually intended.
http://i.imgur.com/mjiCjtt.png

### Back to desktop breakpoint
Notice the white gap next to the menu and the page overflowing (and scrolling) off-canvas:
http://i.imgur.com/DuEyP0U.jpg

**Comment by jamesalley** [comment]
Check http://stage.purecss.io and let me know if it's still a problem. I've fixed that issue in the latest release (I hope). It's on stage now, and if all goes well I'll formally release Pure 0.6.0 next week.

**Comment by jamesalley** [comment]
Thanks for reporting this, btw, and in such detail.

**Comment by jamesalley** [comment]
BTW this is not a bug in grids, it's a bug with the custom menu implementation.

**Comment by MattGreyDesign** [comment]
It seems to have been fixed on your staging, you should be aware of the page scrolling horizontally when the menu is expanded.
