### ISSUE TITLE
Dropdowns inside Side-Menu layout?

### ISSUE THREAD

**Issue by gregit** [yahoo/pure#446]
Hi, Thanks for the great PureCSS.

How to support dropdowns in Side-Menu template?
http://purecss.io/layouts/side-menu/

I've used the following:

```
        <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
            <a href="#" id="menuLink1" class="pure-menu-link">Contact</a>
            <ul class="pure-menu-children">
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Email</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Twitter</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Tumblr Blog</a></li>
            </ul>
        </li>
```

But the submenu remains hidden.

**Comment by jamesalley** [comment]
At first glance your markup looks correct, per [the example provided](http://purecss.io/menus/#vertical-menu-with-submenus). Can you provide a link to the working code, either on a staging server or a JSFiddle? There may be other styles interfering, or ...?

**Comment by gregit** [comment]
Please find an example here:
http://r3al.org/pure-test.html
Clicking on More doesn't show submenus.
Thanks for the help!

**Comment by redonkulus** [comment]
Please re-open if the issue still exists.
