### ISSUE TITLE
anybody can suggest an external jquery multi level responsive menù that works out of the box with pure?

### ISSUE THREAD

**Issue by badpenguin** [yahoo/pure#451]
anybody can suggest an external jquery multi level responsive menù that works out of the box with pure?
thanks

**Comment by jamesalley** [comment]
While it doesn't leverage JQuery, hopefully you saw this [example script](http://purecss.io/js/menus.js) in the [documentation for dropdowns](http://purecss.io/menus/#dropdowns); let me know if you missed it. Maybe I should make it more prominent. It's just an example script that is ripe for further enhancement; it has basic keyboard navigation support but it could be made more robust.

If you're already loading JQuery on your page, you could easily adapt the example to leverage JQuery conventions and then you'd be able to save a few bytes.

But you don't have to do that; it's vanilla JS so it will work with or without JQuery. 

Again, let me know if you think it needs a more prominent place in the documentation, or if you think it needs work. Or feel free to submit a pull request against the source file, which you can find at https://github.com/yahoo/pure-site/blob/master/public/js/menus.js

**Comment by badpenguin** [comment]
The example script is out of question :) i'm looking for a multi-level menù or maybe a mega-menù.
Jquery its not an issue: i just want to get rid of foundation and/or bootstrap.

**Comment by jamesalley** [comment]
If it's out of the question, there could be several reasons. Perhaps you need edge detection, so that submenus will display to the left or to the right, or to the top or to the bottom, depending on proximity to a viewport edge? Perhaps you need better keyboard support? Maybe the accessibility features need work? I can think of many reasons why you might want something different, or something more, but you asked for a multi-level menu in JQuery. Now that you've decided JQuery is not an issue, what deficiencies remain? Pure Menu does support multi-level menus. I'm trying to tease out what improvements I or anyone else could make and roll into a future release. Can you clarify your needs?

**Comment by badpenguin** [comment]
my main needs is getting rid of foundation/bootstrap; pure.css its ok, i already had a demo project going on my local sever,  but it lacks a menù for complex websites like an e-commerce website - currently i don't have the time myself to implement a full featured complex menù from scratch, i'm forced to search and reuse some kind of existing jquery componenet togheter with pure.css and that's an accetable solution for me

**Comment by jamesalley** [comment]
If you main needs are getting rid of foundation/bootstrap, job done! But it sounds like your needs truly center around the concept of a "menu for complex websites" or a "full featured complex menu". The problem is that I don't understand what those features are, or how a menu for a complex website differs from a menu for any other site. You may not have to start from scratch.

**Comment by badpenguin** [comment]
I hope this helps: http://www.smileycat.com/design_elements/mega_dropdown_menus/
Anyway, does not matter, if you don't have some standard solution to suggest i'll figure it out somewhere else.

**Comment by jamesalley** [comment]
OK, that gives me a better idea of what you're looking for. Perhaps I can whip up an example of such a menu in the future. BTW, of the three menus I viewed in that gallery, none were responsive.

**Comment by jamesalley** [comment]
But I would suggest that creating your own would not be that hard. Use Pure-menu-horizontal for your basic menu and then just show/hide divs for each menu item. Within each mega item you could use Pure again to layout the content with grids etc. You just need JS to toggle the hiding and showing of divs.

As the gallery shows, there are many ways to create a menu like that; it's a very opinionated construct. But again, I will keep this in mind when considering what new examples I could cook up.

**Comment by badpenguin** [comment]
I still prefer a well tested solution.

**Comment by badpenguin** [comment]
What about this one? http://jasonweaver.name/lab/flexiblenavigation/

**Comment by ironbyron** [comment]
Here is a quite helpful resource for responsive design patterns (menus and other elements)
http://bradfrost.github.io/this-is-responsive/patterns.html#navigation

**Comment by jamesalley** [comment]
Interesting examples. the jasonweaver example is intriguing but even just playing with it I can see it has its flaws. (I quickly found myself in a state where many different menus were open and I couldn't dismiss them.)

Some of these complex, highly opinionated examples might be fantastic pieces of work, but I wouldn't hold your breath waiting for such examples to appear in Pure as ready-made, core components. They are just too complex and opinionated. You would use Pure as a source of building blocks to make components like these, but components like these need not be in Pure itself.

**Comment by badpenguin** [comment]
that's the reason because i opened this issue! :-/

**Comment by Carlosxell** [comment]
I like this menu : http://stage.purecss.io/layouts/tucked-menu-vertical/ with only VanillaJS and I think the cool of pureCSS is just not use jQuery or other frameworks but only VanillaJS (pure JS).

I even adapted it to my needs:
http://codepen.io/Carlosxell/pen/RNyqxL

I think of to do more that way and keep the code cleaner....

**Comment by badpenguin** [comment]
Found the solution:

1) >600px: just a normal CSS only multi-level menù
2) <600px: brand+menu toggle and use and off-canvas with : http://www.berriart.com/sidr/#usage
