### ISSUE TITLE
Publish 0.6.0 to NPM

### ISSUE THREAD

**Issue by bebraw** [yahoo/pure#453]
For some reason NPM seems to have 0.5.0. Could you push a newer version there?

**Comment by jamesalley** [comment]
In the past Pure was published to NPM by a third party. However, that person has given us permission to publish it ourselves, so I'm working on it.

**Comment by tivac** [comment]
Hooray!

**Comment by ericf** [comment]
See PR #454

**Comment by jamesalley** [comment]
npm install purecss

done
