### ISSUE TITLE
Loginform Problem IE

### ISSUE THREAD

**Issue by masteradhoc** [yahoo/pure#461]
Im working on a  Login, with pure css. This is my code:
```
            <form id="loginform" class="pure-form pure-g" method="post">
                <fieldset class="pure-group">
                    <input type="text" name="username" class="pure-input-1" placeholder="Benutzername">
                    <input type="password" name="password" class="pure-input-1" placeholder="Passwort">
                </fieldset>

                    <div class="pure-u-2-5">
                        <button type="submit" name="submit" value="anmelden" class="pure-button pure-input-1 pure-button-primary">Anmelden</button>
                    </div>
                    <div class="pure-u-1-5">
                        <!-- nothing to show here-->
                    </div>
                    <div class="pure-u-2-5">
                        <button form="loginform" type="reset" name="reset" value="zuruecksetzen" class="pure-button pure-input-1 pure-button-primary">Zuruecksetzen</button>
                    </div>

            </form>
```

On IE the two Buttons look like this:
https://onedrive.live.com/redir?resid=3D048026C1BFF6E0!31991&authkey=!AEv6QQXkCTNZW60&v=3&ithint=photo%2cpng

on Firefox like this:
https://onedrive.live.com/redir?resid=3D048026C1BFF6E0!31990&authkey=!AFbTxddDU-V06sI&v=3&ithint=photo%2cpng

Is this a Issue or am i doing something wrong?

![ff](https://cloud.githubusercontent.com/assets/6242098/6664204/26622d06-cbce-11e4-896c-8a840886d269.png)
![ie](https://cloud.githubusercontent.com/assets/6242098/6664205/26628fd0-cbce-11e4-82a5-6bbf2aae0600.png)

**Comment by masteradhoc** [comment]
@jamesalley any idea?

**Comment by jasonmit** [comment]
What version of IE?

**Comment by masteradhoc** [comment]
10 in Version 10.0.9200.17267

**Comment by jamesalley** [comment]
I'll take a look at this today.

**Comment by jamesalley** [comment]
I think your problem is that you don't have a grid unit as a child of your grid. As the [Grids docs](http://purecss.io/grids/#introduction-to-pure-grids) say, "All child elements of a grid must be units." 

Here is an example illustrating the fix.

http://jsfiddle.net/james_alley/cka0stzc/

**Comment by masteradhoc** [comment]
Thanks!
