### ISSUE TITLE
Transferring to a new line

### ISSUE THREAD

**Issue by Totoshka12** [yahoo/pure#463]
If you do zoom-out the third column can not fit into a row and transferred.
http://jsfiddle.net/f1oLmnec/
Only Firefox.

**Comment by jamesalley** [comment]
This is a known issue with Firefox, only at certain zoom levels, and it's unpredictable. There is a workaround for this, which I have so far been reluctant to put into pure: set the widths to just a tiny fraction under. So if you're using `.pure-u-1-2` which would normally put the width at 50%, try setting the width to 49.99% or something like that. You can see why I'm not in a rush to put such a hacky solution into pure when it's the browser that has a little bug.
