### ISSUE TITLE
Text alignment in select on Firefox for Mac OS X

### ISSUE THREAD

**Issue by Alko89** [yahoo/pure#474]
There was a small alignment issue in Firefox on a Mac, where the text was not fully visible. I fixed it by adding `padding: 0.4em 0.5em;` to `.pure-form select` in `forms-nr.css`.

![before](https://cloud.githubusercontent.com/assets/2822030/7045567/920afa90-ddff-11e4-8d42-e55495cf627f.png)
![after](https://cloud.githubusercontent.com/assets/2822030/7045566/92085aba-ddff-11e4-97b6-d72c27928e07.png)

**Comment by c-rack** [comment]
@Alko89 Thanks for your solution; I had the same issue.
Additionally, I had to set `height: auto` to avoid a cropped baseline (for characters like "gqpjy").
