### ISSUE TITLE
How to center pure-u-* in a grid?

### ISSUE THREAD

**Issue by durancristhian** [yahoo/pure#477]
Hi devs! I want to do something crazy and I can't figure out how to do it :sweat: 

As a summary, I want to align to the center my .pure-u-\* elements in a certain resolution (desktop in my case) and give them a width: auto;

I have the following markup:

```
<div class="pure-g">
    <div class="pure-u-1 pure-u-md-1-3">
        <a href="#!">Item #1</a>
    </div>
    <div class="pure-u-1 pure-u-md-1-3">
        <a href="#!">Item #2</a>
    </div>
    <div class="pure-u-1 pure-u-md-1-3">
        <a href="#!">Item #3</a>
    </div>
</div>
```

What I want:

![screenshot_2](https://cloud.githubusercontent.com/assets/4248944/7309374/15f2ba50-e9f4-11e4-8884-2e35f5d58953.png)

What I have:

![screenshot_1](https://cloud.githubusercontent.com/assets/4248944/7309377/1e77b66c-e9f4-11e4-95d3-772ab23b97fe.png)

I know that it's something strange what I want to do, and obviously, for this case, it would be more properly if I just use <a> elements without the grid and I change the width of those elements for the different breakpoints. But let's suppose that use a grid is a request. Anyone can suggest me something? or I'm crazy? :cry:

**Comment by stevenvachon** [comment]
They're `inline-block` elements, so putting `text-align:center` on that `.pure-g` should do it.

**Comment by durancristhian** [comment]
@stevenvachon that was my first test with unsuccessfull results

![desctop screenshot](https://cloud.githubusercontent.com/assets/4248944/7322936/a411c7a8-ea81-11e4-9e9e-3ae838382026.png)

I've put a ```text-align: center;``` on the ```.pure-g``` and I've set ```width: auto``` for the ```.pure-u-*``` elements.

**Comment by stevenvachon** [comment]
Honestly, for what you'r building, you probably shouldn't be using grids. Just use `display:block`, `float:left` and `width`

**Comment by stevenvachon** [comment]
As you've said, you're better off with just display:inline-block. But anyway, put together an example on jsfiddle.

**Comment by jamesalley** [comment]
Actually that looks like a good use-case for pure-menu.

**Comment by montalvomiguelo** [comment]
`.pure-g` is using `flexbox`

```
css
.pure-g {
  display: -flexbox;
  align-content: flex-start;
}
```

Pure units are `inlinte-block` so you can center them in 2 ways:

* Applying `text-align: center;` in `.pure-g` 
* Applying `justify-content: center;` in `.pure-g`

[Example here](http://codepen.io/montalvomiguelo/pen/mVJQpq)
