### ISSUE TITLE
How to add an inline form to a menu?

### ISSUE THREAD

**Issue by ljwolford** [yahoo/pure#479]
Hello,

I'm trying to add an inline form to my pre-menu-list but I'm running into some issues. I have tried this so far....

```
<div class="header">
  <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
    <div class="pure-g">
      <div class="pure-u-1-2">
          blah
      </div>
      <div class="pure-u-1-2">
        <ul class="pure-menu-list">
          <form action="" method="post" class="pure-menu-form">
             ...
          </form
        </ul>
      </div>
    </div>
  </div>
</div>
```
but it gives me a white border around the form (which i don't want):

![border](https://cloud.githubusercontent.com/assets/1183373/7398658/627c0e74-ee7e-11e4-9450-5d4cf8c760fb.PNG)

i have tried adding the pure-form to the menu as well but it just makes the form giant sized inside of the menu and i have tried every style to remove a border or outline with no luck. 

any point in the right direction is greatly appreciated!

thank you

**Comment by jamesalley** [comment]
Can you point me to a fiddle or some other URL? I tried whipping up a fiddle with the code you provided but it's far from complete; I can't see the problems you're describing.

**Comment by jamesalley** [comment]
Some other comments on the code provided so far:
  * It's odd to put a `form` into a `ul`, which should only accept `li` elements.
  * Your closing form tag is malformed.

**Comment by ljwolford** [comment]
Sorry that was a bad copy/paste. I created a gist for it....I tried creating a JSFiddle but I couldn't get some of the components to render correctly (that are rendering correctly for me locally) for some reason.

https://gist.github.com/ljwolford/502f5c55e65b911d3001

thanks again for your help

**Comment by jamesalley** [comment]
I'm afraid I don't know how to help you yet, for the following reasons:
  * The gist is not sufficient:
    * I don't have access to any of the other CSS involved (marketing.css). 
    * I can't see what you see.
  * Since I can't see any obvious problem (since I can't see what you see), I still don't know what your problem is in the first place. Your only stated issue was a border around the form, shown in your screenshot, but I can't imagine that a simple border is all you're wrestling with here.
