### ISSUE TITLE
Incorrect border color for pure-button:active  ?

### ISSUE THREAD

**Issue by yazla** [yahoo/pure#480]
Hi,
There is a strange color in pure/src/buttons/css/buttons.css for the border-color property, I am not sure it is a valid value:

```
.pure-button:active {
    box-shadow: 0 0 0 1px rgba(0,0,0, 0.15) inset, 0 0 6px rgba(0,0,0, 0.20) inset;
    border-color: #000\9;   <-- HERE
}
```

When I am trying to include this into my less main file using @import, less parser is recognizing this as invalid input.

**Comment by redonkulus** [comment]
@yazla this was added by @jamesalley for IE8, so I'm not sure if we can remove it.

**Comment by redonkulus** [comment]
This should be fixed now.
