### ISSUE TITLE
Grid system without base CSS

### ISSUE THREAD

**Issue by hmaesta** [yahoo/pure#481]
Hello.

I am using Semantic-UI for a large project, but their grid system is not so intuitive as PureCSS.

Can I use PureCSS Grid System **without** loading the base CSS?

Thank you.

**Comment by loele** [comment]
http://yui.yahooapis.com/pure/0.6.0/grids-responsive.css

**Comment by hmaesta** [comment]
@loele Just add "grids-responsive.css" does not make it happen.

Live examples:
– With just **grids-responsive.css**: https://jsfiddle.net/ac1av3cc/ 
– With **grids-responsive.css** and **pure.css**: https://jsfiddle.net/towz6gcn/

**Comment by jamesalley** [comment]
http://purecss.io/grids/#want-to-just-use-grids

**Comment by jamesalley** [comment]
You can see from that link that you need base, grids, and grids-responsive.

Every part of Pure is available individually, or you can create custom rollups. You can also download the source code and generate your own custom grids.

**Comment by hmaesta** [comment]
@jamesalley It was very embarrassing I have not seen this in documentation.
Thank you.
