### ISSUE TITLE
Responsive horizontal menus don't work on mobile with children classes

### ISSUE THREAD

**Issue by featurereq** [yahoo/pure#483]
I tried both responsive horizontal menus from menus page (under "Responsive Menus That Hide"), but none of them worked when I added children classes. There are multiple issues of which some can easily be solved (like overflow for dropdown menus on desktops), but toggle function simply doesn't work on mobile devices if children classes are used.

How can this be done, please?

Thanks

**Comment by redonkulus** [comment]
@featurereq can you provide an HTML snippet to help understand the issue? Perhaps a jsFiddle example too.
