### ISSUE TITLE
http://purecss.io/layouts/email/ example bug

### ISSUE THREAD

**Issue by nomosyn** [yahoo/pure#485]
![screen shot 2015-05-12 at 14 00 18](https://cloud.githubusercontent.com/assets/2693150/7586646/49349df6-f8af-11e4-8afb-bd401795181e.png)
- A) goto: http://purecss.io/layouts/email/ 
  ![screen shot 2015-05-12 at 13 52 59](https://cloud.githubusercontent.com/assets/2693150/7586651/59cd590a-f8af-11e4-9c0b-43cbae74e0a5.png)
- reduce viewport area so that responsiveness kicks in so that we have:
  ![screen shot 2015-05-12 at 13 53 17](https://cloud.githubusercontent.com/assets/2693150/7586655/667c0eb2-f8af-11e4-963e-b7258337e728.png)
- click the "compose" button:
  ![screen shot 2015-05-12 at 13 53 27](https://cloud.githubusercontent.com/assets/2693150/7586669/839f09fe-f8af-11e4-9eed-73f011aa1026.png)
- B) augment viewport area so that we have:
  ![screen shot 2015-05-12 at 13 53 37](https://cloud.githubusercontent.com/assets/2693150/7586674/918fa51e-f8af-11e4-875c-095bd1982a04.png)

Compare A and B: the left column doesn't go to the buttom of the viewport which is what is expected (... well, what I expected at least...)

**Comment by jamesalley** [comment]
Thanks for the bug report. I can see this is because the nav is still active; it actually has nothing to do with the Compose link. I should add a listener so that when a window change event happens we re-hide the menu, or so that the active class only takes effect within a media query. I'll fix this for the next release.

**Comment by redonkulus** [comment]
Please re-open this in the pure-site repo if it is still a concern. This is not a Pure specific issue and I would like to keep only library issues open here. Thanks!
