### ISSUE TITLE
Hidden attribute !important

### ISSUE THREAD

**Issue by galulex** [yahoo/pure#486]
I can see that `!important` rule [here](https://github.com/yahoo/pure/blob/master/src/base/css/base.css#L17) since 0.6.0 version. Is it required to have the `!important` there? This change makes difficult to update to 0.6.0 version because sometimes I need to display the element with class '.hidden' but with this change i have to add the `!important` rule everywhere.

**Comment by kwando** [comment]
How about removing the ```hidden``` class in that case instead?

**Comment by galulex** [comment]
@kwando I am using it everywhere in my app. I have just done the search in my projects and found 84 matches.

**Comment by kwando** [comment]
Like I said, why not remove the hidden class instead? Or use your own ```.my-hidden``` class?

**Comment by galulex** [comment]
I am able to fix it. But the question is why is the `!important` rule there?

**Comment by kwando** [comment]
See this issue:
https://github.com/yahoo/pure/issues/177

And this changelog entry:
https://github.com/yahoo/pure/blob/8e5d20c423f471d409066f7a94a6c0082fef2031/HISTORY.md#base-1

**Comment by galulex** [comment]
@kwando thank you for your time. I will close the issue

**Comment by jamesalley** [comment]
Nice work addressing this question. Thanks.
