### ISSUE TITLE
在使用menu时发现一个bug

### ISSUE THREAD

**Issue by liuww111** [yahoo/pure#489]
“pure-menu-item pure-menu-has-children pure-menu-allow-hover”使用这个css创建的可以下拉的menu时候发现大小不统一，然后我加了这样一段css
.pure-menu-has-children>.pure-menu-link:after{
    content:normal;
}
.pure-menu-horizontal .pure-menu-has-children>.pure-menu-link:after {
    content:normal;
}将那个小箭头也去掉，就和其他的menu一样大小了

**Comment by liuww111** [comment]
/*参考bootstrap的箭头*/
.pure-caret {
  display: inline-block;
  width: 0;
  height: 0;
  margin-left: 2px;
  vertical-align: middle;
  border-top: 4px dashed;
  border-right: 4px solid transparent;
  border-left: 4px solid transparent;
}
<div class="pure-menu pure-menu-horizontal">
    <ul class="pure-menu-list">
        <li class="pure-menu-item pure-menu-selected"><a href="#" class="pure-menu-link">Home</a></li>
        <li class="pure-menu-item pure-menu-allow-hover">
            <a href="#" id="menuLink1" class="pure-menu-link">Contact<div class="pure-caret"></div></a>
            <ul class="pure-menu-children">
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Email</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Twitter</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Tumblr Blog</a></li>
            </ul>
        </li>
    </ul>
</div>
使用bootstrap的箭头设计会比较好

**Comment by jamesalley** [comment]
For anyone following this, I used Google Translate to glean the following:

Use the pull-down menu can be created when the css discovery size is not uniform, then I added this section...The little arrows are removed, and the other on the same size as the menu...

I looked again, is a problem as long as the arrow to disable this arrow can be unified...

/ Reference bootstrap arrow /
...
Use the arrow design bootstrap would be better

**Comment by liuww111** [comment]
Thank you for your answer, I love pure very much
