### ISSUE TITLE
Load pure from yahooapis cdn network over https fails

### ISSUE THREAD

**Issue by denisj07** [yahoo/pure#490]
I'm trying to load the pure.css file from the provided link (http://yui.yahooapis.com/pure/0.6.0/pure-min.css) i got from the purecss.io homepage in my ssl encrypted webpage, but unfortunately the file cannot be loaded.
Trying to use a https link to the yahooapis site fails again because the certificate they use is untrusted.

Is there any workaround instead of loading pure.css from my webserver?

**Comment by tivac** [comment]
Y! doesn't provide a HTTPS CDN for public use. If you don't have your own HTTPS CDN you could use something like this: https://cdnjs.com/libraries/pure

**Comment by lkraav** [comment]
What's wrong with using https://yui-s.yahooapis.com again?

**Comment by tivac** [comment]
@lkraav not officially supported, last time I asked. Maybe that's changed?

**Comment by denisj07** [comment]
Ah thanks!
Well i don't really have a problem with loading it directly from the local webserver, but using inofficial CDNs and missing the chance that browsers already cached pure from earlier visits on other sites isn't nice either.

So maybe I have to keep loading it from the webserver until there is a official https CDN...
