### ISSUE TITLE
iPhone 5s landscape grid issue (568px)

### ISSUE THREAD

**Issue by felcans** [yahoo/pure#494]
It looks like 35.5em (max-sm media query) doesn't trigger until 567px on most browsers. Which leaves a gap between small and medium breakpoints. I have only noticed because 35.5em (568px) is the exact size of an iPhone 5s in landscape. Medium seems to pick up at 569px. Leaving 568px hanging. It seems like using 35.6em works better for the sm break point.

**Comment by redonkulus** [comment]
@felcans is this still an issue in iPhone 6 and 7 phones?

**Comment by felcans** [comment]
Could not recreate the issue on the 7. I don't have a 6 to try, but if I come across one I'll let you know. I also tried on my 5s again and was not able to recreate it. I'm guessing this could have possibly been a box-sizing issue, or a scenario where a font size was scaling things perfectly inconveniently for me. I'm using pure in several projects at the moment, so if I do run across it I'll be sure to give you a heads up. Thanks!

**Comment by redonkulus** [comment]
Ok I'm gonna close it, please re-open if you see it.
