### ISSUE TITLE
Gallery layout example - photos distorted on resize

### ISSUE THREAD

**Issue by intermedion** [yahoo/pure#496]
When the gallery layout example (http://purecss.io/layouts/gallery/)  is resized, the photos are distorted because the height stays the same but the width is narrower. To reproduce just resize the browser and watch the bridge photo.

**Comment by jamesalley** [comment]
Thanks for the bug report. If you have a PR to fix it please file it against the [pure-site](https://github.com/yahoo/pure-site/) repo. 

I'll mark this as resolved/duplicate because there is already an open issue for this:

https://github.com/yahoo/pure-site/issues/288
