### ISSUE TITLE
Marketing layout is missing a float at .pure-menu-heading

### ISSUE THREAD

**Issue by bebraw** [yahoo/pure#499]
See http://purecss.io/layouts/marketing/ . It renders `.pure-menu-heading` and `.pure-menu-list` on separate rows in Firefox (same row on Chrome). You can make this consistent by adding `float: left` to `.pure-menu-heading`. After that they'll layout as expected.

**Comment by lkraav** [comment]
The whole point of Pure CSS is to avoid flow-breaking floats.

**Comment by bebraw** [comment]
@lkraav Ah, good point! Perhaps that `.pure-menu-list` can be modified somehow. Get rid of its float using some other method.

**Comment by jamesalley** [comment]
Duplicate of https://github.com/yahoo/pure-site/issues/246
