### ISSUE TITLE
Support Horizontal-to-Vertical and Horizontal-to-Scrollable in menu of 'Landing Page' layout

### ISSUE THREAD

**Issue by zhanghuangbin** [yahoo/pure#500]
Dear developers,

Could you please make the menu of 'Landing Page' layout support Horizontal-to-Vertical and Horizontal-to-Scrollable by default? This will save user much time and make PureCSS better.

Thanks. :)

**Comment by jamesalley** [comment]
The layouts are not part of Pure itself, but are examples of how you can build interesting custom solutions on top of Pure. We don't aim to have a library of hundreds of layouts or other hyper-specific solutions. Instead, we aim to provide a solid base from which to begin custom coding-- a base you'd have to write yourself over and over again with each web project, if it were not already in Pure.

Mixing and matching solutions you see in the various examples is thus an exercise for the user. If you work up a Fiddle or other example, and then run into specific problems, I'd be happy to help you figure things out.

In the case of what you're asking for, I can't make that page Horizontal-to-Vertical and Horizontal-to-Scrollable by default. I'd have to create new pages for each case. You can see how if we accommodated every such request for a particular combination of features, the size of the Pure-site would balloon and it would be increasingly hard to maintain.

So go ahead, build it! Ask for help if you need it. And when you're done, if you have a particularly creative solution that would be good to share, perhaps you can submit it to the pure-site for consideration as a pull request.
