### ISSUE TITLE
Don't work the grid CDN

### ISSUE THREAD

**Issue by JuanLuisGarciaBorrego** [yahoo/pure#509]
Hi, I'm starting with PureCSS , but I don't know what use CDN. 

http://codepen.io/JuanLuisGarciaBorrego/pen/wamdVw?editors=110
Don't work the grid CDN

Can you give me help ?
Thank You

**Comment by jamesalley** [comment]
Works for me. What browser and what symptoms?

James

**Comment by JuanLuisGarciaBorrego** [comment]
Thank for you answer.
Now it works, I changed the CRC.
I use this ->
http://yui.yahooapis.com/combo?pure/0.6.0/base-min.css&pure/0.6.0/grids-min.css&pure/0.6.0/grids-responsive-min.css

Is there any CD that includes everything?
