### ISSUE TITLE
Drop down menu arrow missing or incorrect on Samsung tablet, IE8 on Win XP

### ISSUE THREAD

**Issue by robd** [yahoo/pure#510]
This is similar to #277. I am seeing missing or odd unicode replacements for the drop down arrow on the [dropdown menus](http://purecss.io/menus#dropdowns).

I think this is due to limited support for the small arrow unicode symbol \25BE: http://unicode.johnholtripley.co.uk/25BE/

From the above link it looks like it also wouldn't work on Sony phones. I just wondered if I missed something in setting up Pure CSS or whether this is a known issue. Is there a workaround for this (without loading a custom font-face just to fix that one glyph)?

**Comment by devilliersesterhuizen** [comment]
Honestly, Windows XP.
XP should be buried & burned.
Further, I will look into your issue.

**Comment by jamesalley** [comment]
The huge variety of Android builds out there, and the browsers they run, is tough to address.

**Comment by robd** [comment]
@jamesalley Yes, I agree. The reason why I draw attention to this is that on the site I'm working on Samsung are the second most used mobile / tablet brand after Apple (Apple 73%, Samsung 11.5%). To put it another way, we see more Samsung sessions than Firefox sessions.

I guess some solutions to this might include:

- use inline png 
- inline css webfont with this one glyph in it
- inline svg
- [pure css triangles](https://css-tricks.com/snippets/css/css-triangle/)

I don't know if it's worth fixing this, if so I can look into getting a PR together.
