### ISSUE TITLE
for responsive grids, a pure-u-0 ?

### ISSUE THREAD

**Issue by moabi** [yahoo/pure#512]
maybe I didn't see this feature, but I find it useful (sorry if it exists already...)

     .pure-u-0{width:0;display:none;}

    <div class="pure-g">
     <div class="pure-u-0 pure-u-md-8-24"></div>
     <div class="pure-u-1-4 pure-u-md-4-24"></div>
     <div class="pure-u-1-4 pure-u-md-4-24"></div>
     <div class="pure-u-1-4 pure-u-md-4-24"></div>
     <div class="pure-u-1-4 pure-u-md-4-24"></div>
    </div>

**Comment by AndrewGuenther** [comment]
:+1: 

There's some discussion on this at #326

**Comment by moabi** [comment]
:+1:
I was not alone then ;)
