### ISSUE TITLE
Errant \9 in src/buttons/css/buttons.css

### ISSUE THREAD

**Issue by djbusby** [yahoo/pure#515]
In this source file, line #32 there is a code

```
border-color: #000\9;
```

I'm pretty sure that is should just be:

```
border-color: #000;
```

**Comment by gsusmonzon** [comment]
The \9 is probably intended for a rule that applies *only* to IE7 and IE9 ( see https://css-tricks.com/how-to-create-an-ie-only-stylesheet/ ).
Saying that made me feel i am getting old.

**Comment by djbusby** [comment]
Please consider this a vote to not support very old stuff; but I'll understand if we close WONTFIX

**Comment by redonkulus** [comment]
Ya its more likely that we remove support for older browsers, rather than add more support. Closing as WONTFIX.
