### ISSUE TITLE
Useful website examples

### ISSUE THREAD

**Issue by pacav69** [yahoo/pure#516]
It would be useful to have webpage examples to aid in the viewing of the small examples for the developer.

**Comment by ironbyron** [comment]
I have to +1 that, although there are some layouts available.

**Comment by jamesalley** [comment]
Can you elaborate on what sort of examples you'd like to see? (Although, that is a dangerous question, because usually folks ask for a solution to whatever problem they happen to be working on at the moment.)

ironbyron is correct that there are "layouts" on the site which illustrate how you can take something generic like Pure and use it as a foundation for interesting custom designs. Pure is supposed to deal with all the basic stuff you'd have to start off doing anyway before you get into your customizations.

**Comment by pacav69** [comment]
As with all things people can look at code and there others that can best
understand from example depending on their background and how they perceive
things.

I suggest that you describe how to change or override the colors with a
custom.css file so that the menus can have different settings without
straying too far from the intent of purecss. Another example would be a
contact form as opposed to the login form shown on the website as it is
more practical and complete for a blog. Another good example would be using
the menus for page navigation like page 1 of 3 and how-to use the menus to
span across different pages like home, about, contact etc.

I have enclosed the custom.css file that i used on my github page to
illustrates the change of colors.
Here is a link for my github page which uses purecss.
http://pacav69.github.io/komodo-ext-docs/

The example that i found that was a good illustration of purecss.
http://www.w3resource.com/pure/

On Thu, Aug 27, 2015 at 1:16 AM, James Alley <notifications@github.com>
wrote:

> Can you elaborate on what sort of examples you'd like to see? (Although,
> that is a dangerous question, because usually folks ask for a solution to
> whatever problem they happen to be working on at the moment.)
>
> ironbyron is correct that there are "layouts" on the site which illustrate
> how you can take something generic like Pure and use it as a foundation for
> interesting custom designs. Pure is supposed to deal with all the basic
> stuff you'd have to start off doing anyway before you get into your
> customizations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yahoo/pure/issues/516#issuecomment-135111867>.
>



-- 
Paul Cavanagh
Business and IT Consultant
+86-13774291848
------------------------------------------------
http://silverpcgroup.com/
Webhosting and Web Development

Dropbox for Android, iPhone and file sharing
http://db.tt/664PP2JA

For those with smartphones you can scan the QR Code
Paul Cav QR Code
<https://docs.google.com/drawings/d/1gaMyNmCjS1MeiTd8qhX2BU46txJG7N7gDrNCKgJorC0/edit>

**Comment by joshvickerson** [comment]
@pacav69 by examples do you mean something like a showcase of things made with Pure, or more detailed code samples?

**Comment by pacav69** [comment]
@joshvickerson i mean more detailed code samples that demonstrate and explain how to use pure css as shown in http://www.w3resource.com/pure/

**Comment by ruipacheco** [comment]
Up

For example, the menu examples aren't clear on how they interact with grids. And the source for the sample page doesn't seem to correspond with whats on the tutorial.

**Comment by redonkulus** [comment]
Going to close this, but feel free to continue the discussion. There are many examples that exist on the site and in the repository, I'd also suggest that any user created examples be added here to help others.
