### ISSUE TITLE
Pure CSS Not working

### ISSUE THREAD

**Issue by othellobloke** [yahoo/pure#518]
Hey...

Pure CSS used to work perfectly inserting the stylesheet tag in the head and everything worked...

But now, it only works if I save the CSS file onto my local hard drive.  Tried on MULTIPLE sites adding the stylesheet tag in head, and then adding a grid but it just doesn't work.

Help?

**Comment by mauricecruz** [comment]
It'll be easier to help if you provide code samples. 

Taking an educated guess, but this seems more like a network or path issue rather than an actual issue with Pure itself.

**Comment by othellobloke** [comment]
That's what I thought but I used the instructions on the website to the
letter and it just doesn't work.  Hasn't for a while.

Bootstrap css works fine though :(


----------------------------------------------------------------------
Ryan Paul | Life in Canada from a British perspective -
http://www.ryanpaul.ca <http://www.intertribaltimes.com>

**Comment by mauricecruz** [comment]
It's working for me when pointing to the CDN from their readme. If you provide some markup, I can tell you what the problem probably is.

http://codepen.io/anon/pen/OyPPLv
