### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by sterpe** [yahoo/pure#520]

**Comment by okuryu** [comment]
See #414.

**Comment by sterpe** [comment]
Unless Yahoo is on a significantly different business quarter cycle than the rest of the universe it doesn't seem like there's been much action toward the remaining 2015 goals listed in #414 ...so the question about the current state of Pure still stands.

**Comment by tivac** [comment]
@sterpe https://github.com/yahoo/pure/issues/414#issuecomment-132315132

**Comment by sterpe** [comment]
Thanks
