### ISSUE TITLE
tip: for users who would like to use less to override colors of purecss

### ISSUE THREAD

**Issue by pacav69** [yahoo/pure#523]
# Tip

Here is a tip for users who would like to use less to override colors of purecss.
## Using a custom.css file to override the purecss colors in combination with less.

First make sure you have the CDN style sheet in the head tag
next add in a custom.css style sheet.
## Creating the less files

Create a custom.less file
then create a palette.less file
make sure that they are in the same directory

In the custom.less add this line

```
@import "palette.less";
```

this will import the data contained in the palette.less

For example to override the body and content colors add these lines into custom.less

```
body {
background:@color-primary-0;
}
#content{
background:@color-primary-2;
}
```

there are many color overrides available depending on your purecss selections

Next visit:

[paletton color schemer](http://paletton.com/)

this website allows you to select your color scheme
- choose the color scheme 
- from the web page choose tables/export
- select the option less 
- this opens up a new page 
- select and copy the text
- paste this text into palette.less

it will have something like this:

```
..............
/* MIXINS */

/* As hex codes */

@color-primary-0: #283300;  /* Main Primary color */
@color-primary-1: #1F2800;
@color-primary-2: #344302;
@color-primary-3: #556E00;
@color-primary-4: #7DA100;

.............
```
- run your favorite less compiler
## What happens

The compiler will import the contents from palette.less and replace the @color-primary-x, where x is the number, with the values and create a custom.css

this will result in the following:

custom.less

```
body {
background:@color-primary-0;
#content{
background:@color-primary-2;
}
```

custom.css

```
body {
background:#283300;
}
#content{
background:#344302;
}
```

the advantage is that you can revisit [paletton](http://paletton.com/) and repeat the process.

**Comment by redonkulus** [comment]
@pacav69 Thanks for the tip!
