### ISSUE TITLE
Background Image disappearing

### ISSUE THREAD

**Issue by RonnieBDarmis** [yahoo/pure#530]
When using the marketing layout and replacing the background color with an image, my image will initially appear in the Coda 2 preview, but as soon as I refresh it disappears. the only code I've changed in marketing.css is the removal of the background property under .splash-container and the addition of:

background-image: url('img/bg.jpg');
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;

in its place.

Any ideas?

Thanks.

**Comment by kalicki2k** [comment]
I do not know, maybe this can help you: http://jsfiddle.net/V7KSb/5/ 
It is important to set the html and body tag "height" to 100% plus your .splash-container.

**Comment by ACreativeBender** [comment]
Ronnie, 

Did you get this figured out? I'm also having the same issue and I don't understand why.

Thanks!
