### ISSUE TITLE
css classes naming

### ISSUE THREAD

**Issue by dnano91** [yahoo/pure#531]
I just wanted to note here, that I really dislike this kind of naming conventions for css classes (e.g. "pure-menu-item pure-menu-selected")

PureCSS looks really nice and simplistic and I would love to use it, but why do you have to make naming classes so inconvenient and ugly? Same as bootstrap this does not look nice at all in the code and adds so much useless text. Why not use something similar to Semantic UI (e.g. "pure menu item selected")? This would be a lot nicer.

**Comment by lkraav** [comment]
This sort of thing can only be diagnosed on a full prototype project level, so everyone could see and compare. Your example also has different types of baggage associated with it. So the question do we just switch one set of problems for another, and which problem set is less expensive on global scale.

**Comment by dehuszar** [comment]
I would argue that unless all the visual classes are removed, none of these libraries will ever be "semantic".  The main reason is to avoid specificity collisions.  If you're using a pre-processor, you can always [remap the framework classes to a more contextually meaningful class in your markup](https://medium.com/@dehuszar/semantic-remapping-with-css-pre-processors-906ba1a9910c).  The article discusses the use of LESS, but I just [created a plugin to do this with PostCSS](https://github.com/dehuszar/postcss-reference) as well.

**Comment by brandonreid** [comment]
@dehuszar Great article man!

**Comment by dehuszar** [comment]
@brandonreid Thanks!  I'm literally working on my follow-up article comparing sass, Stylus, and PostCSS's ability to do the same strategy right now.  Should be ready soon.

**Comment by danicholls** [comment]
What about making Sass/Less files available that break out class names by module to be defined? So, a partial (or whatever) has `$pureformhoriz = "pure-form-horizontal"` and I change it to a BEMish `form--horizontal` or anything I like. Further down the line there's `.#{$pureformhoriz} { ... }`, so on build it's all the same.

**Comment by lvitali** [comment]
Vx‎,, c ,v‎. ,v‎.,vf. , c, ,v                                                                                                                                     ,but Voucher codes, *Rep.,  ly To: yahoo/pu,greSubject: Re: [pure] css classes naming (#531) , c ‎What about making Sass/Le.,) vu.ss . files available that break out class names by module tke.vo be #nodejs. ,# cdxe.vx #3defi.,ned? So, a partial (or whatever) has $pureformhoriz = "R$ ure-form-my civil x  x vxhorizontal" and I change it to a BEMish form--hor, c the izontal or anything I like. Further down the line there's .#{$pvu,ureformhor.cx. ,xiz} { ... }, so on build it's all the same.

,ve ve, c—vu,‎ #d Reply to this email directly or view it on GitHub.x#R$ , but, not.  the

**Comment by dehuszar** [comment]
@brandonreid You can use LESS or [PostCSS-Reference](https://github.com/dehuszar/postcss-reference) to remap the class structures to whatever pattern makes sense to you.  [Here's the general idea](https://medium.com/@dehuszar/semantic-remapping-with-css-pre-processors-906ba1a9910c#.cgfwccu5o).

**Comment by brandonreid** [comment]
@dehuszar Yeah I ended up doing something similar, thanks yo!

**Comment by dehuszar** [comment]
@brandonreid  Ha, sorry about hitting you twice with the article.  For some reason I got notified as though your previous comment was a fresh post.  Apparently I wasn't paying attention when I reposted.  Not intentionally trolling I promise.  ;-P
