### ISSUE TITLE
CDN does not work over HTTPS

### ISSUE THREAD

**Issue by fulldecent** [yahoo/pure#532]
http://yui.yahooapis.com/pure/0.6.0/pure-min.css

https://yui.yahooapis.com/pure/0.6.0/pure-min.css

This produces mixed content warnings for pages that use HTTPS, which should be all pages.

**Comment by lkraav** [comment]
Use https://yui-s.yahooapis.com

**Comment by fulldecent** [comment]
Awesome, thank you
