### ISSUE TITLE
Responsive menus are broken with Mozilla mobile browsers since 42.0

### ISSUE THREAD

**Issue by ganskef** [yahoo/pure#533]
PureCSS layouts with responsive menus are working for me with Mozilla mobile browsers up to version 41.0, but are broken with 42.0 (tried with https://ftp.mozilla.org/pub/mobile/releases/43.0b4/android-api-11/multi/ too). 

The menu button not usable. Note: after zooming the layout, it's working and you can open the menu. Back on normal size, it's disabled again. 

It's simply reproducible with http://purecss.io/ and with multiple Android phones from Version 4.4 to 6.0. I haven't tried a tablet. But, I've tried it with Mozilla Firefox 42.0 on Mac OS with no problem.

**Comment by Goury** [comment]
Works fine with both style "p-menu p-menu-horizontal p-menu-scrollable" and on purecss.io on mine 45.0@5.1

**Comment by ganskef** [comment]
Yes, I've confirmed it with http://purecss.io/ and http://apple.com/ additionally. Both are showing the same effect. It seems to be fixed in Mozilla Firefox.

The menu works fine with Firefox mobile 44.0.2 and it *fails* with 43.0b4.

Should I close this issue?

**Comment by ganskef** [comment]
I'm closing this issue since it's fixed in Mozilla Firefox mobile. 

Sorry, it was a blocking problem for me, so I've switched the framework.
