### ISSUE TITLE
Responsive Horizontal-to-Vertical Menu + Dropdown

### ISSUE THREAD

**Issue by ryanbuiltthat** [yahoo/pure#535]
Are there any examples using the horizontal to vertical menu with dropdowns? Doesn't seem to support them out the gate.

**Comment by caissalover** [comment]
Guys, please help with this. Dropdowns seem to hide behind the edge of horizontal menu, like shown in the image below.

![screenshot](https://user-images.githubusercontent.com/42798632/91486144-7a879d80-e8c9-11ea-8bad-9c69ef6d3797.png)

**Comment by redonkulus** [comment]
Haven't looked into this myself, is there an overflow setting cutting it off? Can you dump this into a code sandbox to demo?

**Comment by caissalover** [comment]
Yes, but that overflow setting helps to hide the vertical menu on the next line for small widths. If I disable the overflow setting, the horizontal menu is visible on next line even without toggle.
