### ISSUE TITLE
Responsive Side Menu Shrink-To-Fit Issue

### ISSUE THREAD

**Issue by yannnova** [yahoo/pure#542]
The Responsive Side Menu needs shrink-to-fit=no added in order to stop Safari iOS9 from rescaling the #main content.

Once this is fixed another issues comes up, the viewport height seems to get scaled up, so if you activate the menu from the bottom of the page the menu-link will disappears and the top of the menu will be cut off.

**Comment by redonkulus** [comment]
@yannnova is this still an issue in iOS10? If so, please re-open.
