### ISSUE TITLE
Change documentation to load pure-css from a https enabled cdnjs instead of yui.yahooapis.com 

### ISSUE THREAD

**Issue by sheki** [yahoo/pure#549]
The docs suggest using this https://i.imgur.com/r9zyZlL.png yui.yahooapis.com
That does not support HTTPS form what I can tell.
Pure is available on cdnjs over https, so the docs should suggest downloading from there ?

**Comment by daverogers** [comment]
Agreed. Ran into that today, switched to cdnjs.

**Comment by mhulse** [comment]
Just found #532, which suggests to use: <https://yui-s.yahooapis.com/>

**Comment by schiz0id** [comment]
Agreed. All was well until I launched my site and Cloudflare was set to require https.

**Comment by prashantbarca** [comment]
Created a PR for this - #588

**Comment by redonkulus** [comment]
Merged #588.

**Comment by redonkulus** [comment]
Once the new release process is in place, we will be advocating for cdnjs anyways and away from Yahoo's CDN.
