### ISSUE TITLE
Pure-g in firefox problem

### ISSUE THREAD

**Issue by vimanetdbledzinski** [yahoo/pure#550]
Objects with pure-g class don't have display set to 'flex' nor flex-flow set to 'row wrap'.
I had to set those properties manually.

Tested on:
Nazwa   Firefox
Wersja  43.0.4

Windows 8.1

**Comment by grahamlicence** [comment]
There's a pull request open that would fix this  #543

**Comment by jheander** [comment]
Can confirm that the pull request solves the issue. Any plans for a merge and new release?

**Comment by lkraav** [comment]
Yes there are, but it's about a month or so away.

**Comment by pixeline** [comment]
Looking forward to that!

**Comment by redonkulus** [comment]
Replaced by https://github.com/yahoo/pure/pull/617
