### ISSUE TITLE
Confused which css I need

### ISSUE THREAD

**Issue by zevero** [yahoo/pure#554]
I use the pure-min.css but it seems to be missing
grids-responsive-min.css
The other files seem to be included.
Why is pure-min.css not the whole thing?
Please state it more clearly that this needs to be inserted, but other part (forms, buttons, tables) not.

**Comment by lkraav** [comment]
Details are here http://purecss.io/grids/#pure-responsive-grids

Let us know if there's anything unclear about those paragraphs.

**Comment by zevero** [comment]
Ok ... yes it's all there. And I got it now.
However - as an average newcomer - it is kind of complicated and not so pure as the name suggests...
You have pure-min.css and pure-nr-min.css
This implied for me, that we have a responsive and a non-responsive version, so I thought I do not need it - despite documentation - which I read, but regarded as outdated, since it did not match my mindset...
So after not beeing able to build some responsive forms I finally included it. And now I was unsecure, if I had to include the other parts as well. Looking at the code resolved this, but still I was kind of frustrated.

Ok media queries can not be overwritten. But why do we have a nr version then?

**Comment by lkraav** [comment]
> Ok media queries can not be overwritten. But why do we have a nr version then?

Totally fair question and I really don't know. I've never had use for it. We'll be sure to conduct a user survey going forward. I have a feeling the non-responsive library serves no purpose and can be discarded going forward, but I'll let survey data tell the story.
