### ISSUE TITLE
purecss vs bootstrap?

### ISSUE THREAD

**Issue by sundyxfan** [yahoo/pure#555]
Purecss and bootstrap difference in what? How IE compatibility?

**Comment by jiaxunjiaxun** [comment]
It is a lightweight CSS framework. the difference, I think, is the purpose of design~

**Comment by KrisSiegel** [comment]
Also need to account for maintenance. PureCSS has been essentially untouched for over a year. There are even more alternatives out there if you want something lighter than bootstrap but still fairly full featured (honestly bootstrap isn't *that* heavy; you don't even need the JavaScript if you just want the CSS pieces).

**Comment by pimbrouwers** [comment]
I disagree. Bootstrap is definitely heavy. But here's how I think you should look at it.

Are you building a webSITE? Then go with pure and some custom styles.

Are you building a webAPP? Then go with TWBS or Foundation. They offer many more complete solutions out of the box (modals, tooltips, blah blah blah). That will allow your development to focus on features not appearance.

**Comment by redonkulus** [comment]
Feel free to keep discussing but closing the issue.
