### ISSUE TITLE
Responsive side menu in MSIE is jumpy

### ISSUE THREAD

**Issue by Stevepatd** [yahoo/pure#556]
The responsive side menu, as is used on the purecss.io website, is jumpy with IE 11.  Each click on the side menu will result in the page 'sliding' in from left to right.  Works fine with Firefox, Safari, Chrome.

**Comment by allanesquina** [comment]
Hi guys, you will also see the slide animation doesn't work correctly with the `#layout` element.
In the `side-menu.css` at line `32` should have a `left: 0` property to complete the animation frame from `0` to `150px`. BTW, how about to use `translate` instead? 
Thanks, Regards.

**Comment by redonkulus** [comment]
This was fixed in https://github.com/yahoo/pure-site/commit/a3ce38fea1f1a5c725a28c93bf30294e83771ed8

**Comment by joseAndresGomezTovar** [comment]
@Stevepatd To avoid the "jumpy with IE11" you should change transition time to 0.
`#layout,`
`#menu,`
`.menu-link {`
`    -webkit-transition: all `**0**` ease-out;`
`    -moz-transition: all `**0**` ease-out;`
`    -ms-transition: all `**0**` ease-out;`
`    -o-transition: all `**0**` ease-out;`
`    transition: all `**0**` ease-out;`
`}`

**Comment by joseAndresGomezTovar** [comment]
this could be a better solution:

`@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {`
`    /* IE10+ CSS styles go here */`
`    /*`
`    Add transition to containers so they can push in and out.`
`    */`
`    #layout,`
`    #menu,`
`    .menu-link {`
`        -webkit-transition: all 0s ease-out;`
`        -moz-transition: all 0s ease-out;`
`        -ms-transition: all 0s ease-out;`
`        -o-transition: all 0s ease-out;`
`        transition: all 0s ease-out;`
`    }`
`}`
