### ISSUE TITLE
npm module should export something useful

### ISSUE THREAD

**Issue by bugeats** [yahoo/pure#565]
Right now the npm module will install the css files in `./build`, which is nice, but the module itself doesn't do anything. 

If you are working on a node project that depends on purecss, there is no stable way to access the built files. npm v3 does not place the files in a predictable place. You can't reliably `fs.readFileSync('node_modules/purecss/build/pure.css')`.

I suggest creating a basic `index.js` file that would export fully qualified paths to the built files. Example:

``` javascript
const purecss = require('purecss');

purecss.getFilePath('pure-min.css'); // "/foo/system/node_modules/purecss/build/pure-min.css"
```

You could also have the module export buffers of the file contents.

**I went to implement a PR on this myself, but it wasn't clear how the contents of the published npm package is constructed**. `npm run prelease` doesn't do what I expected. Might want to update docs about that.

**Comment by redonkulus** [comment]
@bugeats why aren't the files in a predictable place? They should always exist under `node_modules/purecss`, at least for NPM 3. Alternatively, you could use [resolve](https://www.npmjs.com/package/resolve) to locate the package consistently.

**Comment by bugeats** [comment]
It's been a while, so I'm not totally in touch with my original grievance. I must have been trying to read the CSS files at runtime. However, from this new perspective I feel like my original issue description is pretty good.

Since this ticket was opened both npm v4 and Yarn were released with different strategies for organizing module files. Both make use of the `main` parameter in `package.json` to explicitly state where the module begins. I still think it would be good to "export something useful". 

https://docs.npmjs.com/files/package.json#main

**Comment by redonkulus** [comment]
There might be a usecase for this with the pure site as well. I can look at doing something similar to your proposal.

**Comment by KristerV** [comment]
Landed here from google looking for a way to use purecss npm properly with react. Found this: https://www.npmjs.com/package/react-purecss
