### ISSUE TITLE
purecss.io unreadable in firefox 46 GTK3

### ISSUE THREAD

**Issue by edwintorok** [yahoo/pure#567]
On Firefox 46.0 the background color is almost the same as the body color making it near impossible to read most of the text: ![Firefox 46.0](https://cloud.githubusercontent.com/assets/721894/15185181/b66a6624-17a0-11e6-8908-947bcd8e6226.png)

On Chromium it looks fine: ![Chromium 51.0.2704.36 (64-bit)](https://cloud.githubusercontent.com/assets/721894/15185182/b6843dec-17a0-11e6-9b1a-dbcb2dcb8afb.png)

Maybe its just that the page has no background color defined and uses the system default which depends on the GTK theme?

**Comment by PauloFrancaLacerda** [comment]
I'm using FireFox 47.0b4 on Windows 7 (x86), and the pure website looks perfect, very close to your Chrome print.

**Comment by lkraav** [comment]
Yes, this is a known issue with the GTK3 transition.

**Comment by redonkulus** [comment]
@edwintorok if you just add `background-color: #fff` to the `body` selector, does that fix it for you?

**Comment by lkraav** [comment]
@redonkulus yeah, for some reason GTK3 doesn't set a default background color.

Upstream doesn't seem to see an issue https://bugzilla.mozilla.org/show_bug.cgi?id=1268618

It sort of makes sense to expect the webpage to set its own background color, but this just isn't an intuitive end result for the user.

**Comment by redonkulus** [comment]
ok thanks. https://github.com/yahoo/pure-site/commit/d905c72b652ab6427a8e020ae9c5cd76ccbfc2c8 fixes it. Will close this out.
