### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by davidwparker** [yahoo/pure#568]
Question:
Is this project actively being developed?
As of the time of this submission, there's 91 issues and 20 PRs.

Nothing has been released in at least a year.

I'm a big fan of this project, but I would love to see it getting active support and I'm afraid that it's falling behind the times (lack of flexbox, etc).

**Comment by Edwardzyc** [comment]
Why don't you volunteer your time to contribute?

**Comment by davidwparker** [comment]
@Edwardzyc - I would, but I'm:
1. Not that great at CSS.
2. Not a contributor to this repo.
3. Not going to fork this repo and "hope" that people follow me.

If I was (1) and (2), I would for sure.

**Comment by okuryu** [comment]
See: https://github.com/yahoo/pure/issues/557#issuecomment-219616086

**Comment by davidwparker** [comment]
Thanks @okuryu - I missed that.
