### ISSUE TITLE
Firefox understands flexbox but the pure-g ruleset is only using prefixed entries

### ISSUE THREAD

**Issue by bunnymatic** [yahoo/pure#569]
It seems that Firefox doesn't like the way flex is defined for the `pure-g` element.

Included here are two screenshots before and after a little mod (which i'll add in this PR) that adds `display: flex` for Firefox.

Pure 0.6.0
![Using Pure 0.6.0](https://cloud.githubusercontent.com/assets/427380/15458430/dc0e56cc-204e-11e6-9c7b-0162ad8f6be3.png)

After my `display:flex` override
![With a manually applied override](https://cloud.githubusercontent.com/assets/427380/15458435/e769b354-204e-11e6-905c-78b977f91e4c.png)

You can see how with the current 0.6.0 version, Firefox does not apply any `flex` to the row.

PR coming soon.

**Comment by lkraav** [comment]
Heya. Thanks for the effort, but this has already been addressed via multiple PR-s before. Things are simply waiting for #557 to resolve.

**Comment by bunnymatic** [comment]
No problem.  Looking forward to the next release.
