### ISSUE TITLE
need help with .pure-g

### ISSUE THREAD

**Issue by zackmorgs** [yahoo/pure#571]
Hey guys, I was looking for a lightweight and minimal grid system to use for scaffolding a site. Pure seemed to fit my needs. 

I did what the site said in documentation and [included the css](http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css) but .pure-g css is not included which breaks the grid system. I'm sure you guys know about this, but I was wondering what the thought process was behind it.

**Comment by VincentN** [comment]
.pure-g is included in grids(.min).css... The grids-responsive(.min).css just contains the breakpoints, so it just builds upon grids.css.

**Comment by lkraav** [comment]
^^^^ is correct, closing.
