### ISSUE TITLE
Content on purecss.io about grids wrong and/or css file content wrong

### ISSUE THREAD

**Issue by styxxx** [yahoo/pure#572]
Hi,

the text on http://purecss.io/grids/ is talking about "pure-u-[number]" classes and breakpoints like 568 pixel for the pure-u-sm-\* classes. But the linked css file http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css has a completely different content: pure-u-[number] and pure-u-[number]-[number] classes are completely missing. The breakpoints are based on "em" not on "px". 
I'm not sure if the manual is wrong or the css file. There are no classes for grids on a screen smaller than 35.5em in that file. And that's pretty confusing.

**Comment by Celti** [comment]
You're looking at the minified CSS, so it's hard to see them, but they are all actually there — and the docs do already explain the reason why they use em instead of px.
