### ISSUE TITLE
Fix CSS validation

### ISSUE THREAD

**Issue by rodfersou** [yahoo/pure#575]
Today W3C CSS validator says that there are 118 erros, I just can't use Pure in my projects because of that.

http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fyui.yahooapis.com%2Fpure%2F0.6.0%2Fpure-min.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

Can someone figure out if it is possible to fix it?

**Comment by absalomedia** [comment]
Most of them are related to vendor specific CSS rules not in the W3C CSS spec, such as IE7 hacks, zoom, various opacity/filters and text-rendering.

Removing IE7 & below rules, along with autoprefixer fixes, will resolve most of these errors.

**Comment by rodfersou** [comment]
amazing! do you mind to create a pull request with your changes as a starting point?

**Comment by rodfersou** [comment]
or you just change normalize version?

**Comment by absalomedia** [comment]
My current custom build (which I'm using in all my Pure related repos on Github) does the following:

1. Uses node edition of Normalizer
2. Modifies an edition of @lkraav autoprefixer with extra IE8+ only compliance & patches it into /src directory - which I've done a PR for @lkraav 's work
3. Modifies an edition of Rework Pure Grids for IE8+ only & patches that into core Node files - PR submitted for this.
4. Adds in pure-u-0 elements into Rework to hide or show grids based on media queries.  - PR already done
5. Adds in 7th based grids for calendar views
6. Only uses the responsive edition of each Pure core file.
7. Then packages all the relevant files into a pure.min.css file with an associated source map

I'm currently investigating how to get multi level menus back working in Pure 0.6 & above using this custom build. Multi level responsive menus were removed in 0.5.0 and I need Pure to work with them for some clients. So even then, my build is still in a state of flux.

As such, there really isn't a way to do a PR with everything I've done in it just yet. Rework Pure Grids being a separate repo that Pure relies upon factors into this.

**Comment by rodfersou** [comment]
ok.. I'll wait so

**Comment by absalomedia** [comment]
Now down to 12 CSS errors on Jigsaw with further revisions to my custom build..

**Comment by rodfersou** [comment]
@absalomedia any chance to make a pull request to master?

**Comment by absalomedia** [comment]
@rodfersou the current pull request I've done is linked into #551 as it does further patches to @lkraav 's work. He will need to merge my fixes into his PR before it even comes close to a PR merge here

**Comment by rodfersou** [comment]
nice

**Comment by absalomedia** [comment]
How should I do this? My initial strategy was to let @lkraav merge all my changes into his build & then let him roll it all up into a PR here..

Is this strategy still current?

**Comment by redonkulus** [comment]
@absalomedia that makes sense to me. See if you can coordinate a PR to his fork and get that in first.

**Comment by absalomedia** [comment]
@redonkulus I've already done a PR for @lkraav to merge my work inside the Pure core into his fork

**Comment by redonkulus** [comment]
Ok great!
