### ISSUE TITLE
Dropping IE7 compatibility

### ISSUE THREAD

**Issue by absalomedia** [yahoo/pure#576]
As Pure seems to be moving towards autoprefixing rules for CSS, I've noticed that it still retains a lot of rules for IE7 and below. It's my suggestion that we drop any IE7 based rules for completeness.

While I can do a patch for this repo using @lkraav 's work (with some extra revisions), we also need to apply a similar change to [Rework Grids](https://github.com/yahoo/rework-pure-grids) package.

Two questions
1. How will the Rework Grids package be managed in the longer term? Inside Yahoo or outside it?
2. What is the reasoning for maintaining IE7 & below compliance, if any?

**Comment by lkraav** [comment]
I'm pretty sure everything involved is moving out of Yahoo. It doesn't look like https://github.com/yahoo/rework-pure-grids was used for anything else.

IE7 will definitely dropped in the upcoming work.

**Comment by absalomedia** [comment]
@lkraav  I can patch Pure Grids now & release a new package via NPM to help speed the transition if you want?

**Comment by lkraav** [comment]
Organizational issues are holding the transition up, not so much patching. But pull requests are welcome.

**Comment by absalomedia** [comment]
Pure Rework Grids now has the relevant [pull request](https://github.com/yahoo/rework-pure-grids/pull/13) for IE8+ only. I've also rolled up the [outstanding PR](https://github.com/yahoo/rework-pure-grids/pull/10) that allows for media queries to hide grids using pure-u-0 variants into it as well.

**Comment by absalomedia** [comment]
Hey @redonkulus who becomes the maintainer of Rework Grids in this respect so we can the whole IE8 thing on the way?

**Comment by redonkulus** [comment]
@absalomedia that would be @lkraav and his team. 

On a side note, it would be interesting to think about which versions of IE should be supported. Does it make sense to maintain for IE8 still?

**Comment by absalomedia** [comment]
@redonkulus I do believe there's minimal (to no?) changes between the IE8+ build work I've done and IE9. The only real issue I've had to account for was the [table issue with IE10/11](https://github.com/yahoo/pure/pull/504). 

I'm thinking it would be best to roll up from IE6 to IE8+ as a point release & then drop IE8 and hopefully IE9 once they drop well below 1% browser coverage worldwide in further releases

**Comment by redonkulus** [comment]
Makes sense to me.

**Comment by redonkulus** [comment]
Fixed now
