### ISSUE TITLE
A pure HTML5 implementation

### ISSUE THREAD

**Issue by Themanwithoutaplan** [yahoo/pure#577]
I'm looking at using PureCSS on a project but the number of divs scares me. Are there any plans for an implementation that makes more extensive use of the HTML5 semantics such as nav, aside, heading, etc?

Or is this already possible because of the attempt to avoid "elemental" selectors?

**Comment by lkraav** [comment]
I wouldn't be against a clean up job, but can you provide a quick example of what you think would be the "HTML5-optimized" structure?

**Comment by joshvickerson** [comment]
Wouldn't the "correct" structure be highly subjective based on content? I thought one of the main goals of HTML5 was to increase semantics. How much would we really save by doing this? `<nav>`, `<aside>` and `<header>` all behave like divs anyway.

**Comment by Themanwithoutaplan** [comment]
I've created a [gist](https://gist.github.com/Themanwithoutaplan/731eac373d2709b35c6b1350b52886b0) based on the responsive menu template. Works pretty well apart from the grid.

@joshvickerson It's not really about saving the number of elements in the DOM. It just makes the whole stuff a lot easier to work because you're structuring semantically. With standardised semantics you **can** rely a lot more on the element. This makes a lot of sense in a CMS context.

Discussions about semantics probably take place within particular content blocks, which is fine because classes can help here.

**Comment by redonkulus** [comment]
The main purpose of the examples is to show how the framework can/could be used. Which tags to use are left to the user as it pertains to their application or site. I'm open to PR's adding more semantic meaning to the examples, but this would be community driven.
