### ISSUE TITLE
Is it necessary to give a class to all li menu items?

### ISSUE THREAD

**Issue by fearnowrath** [yahoo/pure#579]
So i saw in the example code that the li items need to have a class even if they are inside a ul. Copied from the docs below:

```
    <ul class="pure-menu-list">
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Flickr</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Messenger</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Sports</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Finance</a></li>
        <li class="pure-menu-heading">More Sites</li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Games</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">News</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">OMG!</a></li>
    </ul>
```

Isn't it a bit verbose? Is there a way to make it work without the li items the class pure-menu-item and just giving a proper class to the ul?

**Comment by battaglr** [comment]
@fearnowrath, which would be the benefit on doing that?

**Comment by fearnowrath** [comment]
Sorry i don't properly get what you are asking. If you are asking what is the benefit of avoiding to add classes to those li's then its obvious, i dont see the benefit in having to add a class to each li. 

can't it be something like this? 


```
  <ul class="pure-menu-list">
        <li><a href="#" class="pure-menu-link">Flickr</a></li>
        <li><a href="#" class="pure-menu-link">Messenger</a></li>

    </ul>
```

**Comment by battaglr** [comment]
@fearnowrath, yes, sorry for my English, that was the question.

I understand that you wouldn't have to write that class in your HTML. But is there any drawbacks that you can think of?

**Comment by fearnowrath** [comment]
@battaglr the drawback which i can think of is why write extra stuff when its not necessary. bootstrap doesn't need that as far as i know. Another thing is, it will reduce maybe a few bytes from the total page size although that is not so significant but still.

**Comment by battaglr** [comment]
@fearnowrath, well, that's not a drawback, you repeated what you see as a benefit again.

If *avoiding to write a class* is the only thing that you can identify as benefit, I think it's a cheap price to pay. Some consecuentes of removing the class:

1) You're restricted to use only `li` elements. While this may be usually the case, you may need to use something not as descriptive or ideal, like a `span` or a `div` —you gain flexibility to face situations when thinks may not be ideal.

2) Most of the time, or at least half of the time you're going to use some king of template engine, or whatever allows you to create small chunks of reusable code —so writing the class should not be a big issue if you only write it once or twice.

3) You will need to create a selector with higher specificity, making it harder to override. Maybe Pure could introduce some kind of variation for the menu in the future, or maybe you would need to tweak things a bit, and to do that the selector should be at least the same weight as the original.

By adding just a simple class, you can make things a bit more flexible. My two cents.

**Comment by agauniyal** [comment]
It's not about page size, but it increases the amount of refactoring sometimes we have to do. I get it, just use multiple cursors and all, but sometimes it is annoying. Also sometimes we don't use template engines in every other code and it becomes a hassle with so much repeating code.

**Comment by krebbi** [comment]
it is about the size. 
Having just some kilobytes on a IoT-Devices the size of HTML is quite important.

**Comment by battaglr** [comment]
@krebbi, after gzip that difference should be irrelevant. 😀

**Comment by fearnowrath** [comment]
@battaglr  i agree with @krebbi i agree. most of the on page optimzation checking tools suggest to increase the text to code ratio as well so definitely those things really matter.

**Comment by mihokovic** [comment]
When there are classes on all elements (focusing on `li` items you mentioned), it's much easier to adapt a CSS framework to any CMS (if you're using **sass** or **less**).

Let's take WordPress for example.
In WordPress, menu items have a `menu-item` class by default.
Using sass you could do this:
`.menu-item {
  @extend .pure-menu-item;
}`
and you literally merged those 2 classes, and made WordPress menu look like Pure menu.
Of course same thing should be done for the parent `ul` by using `@extend .pure-menu-list`, as well as child anchor `.pure-menu-link` and possibly more elements.

But this way you avoid any hard-coding of a PHP framework, and this is maybe an another answer to your question why Pure has class on `li` items :)
They probably want to make it easy for everyone to adapt their framework to **anything**.

**Comment by redonkulus** [comment]
I don't think this is going to change anytime soon. The classes make it more flexible and ensure that Pure does not need to enforce any markup structure. Plus, the added class weight gzip's well when transferred over the wire. Plus you could extend Pure and apply the same styles to the LI yourself.

I'm going to close this but feel free to continue the discussion. Thanks!

**Comment by fearnowrath** [comment]
Well most other frameworks are doing fine without this kind of approach and I really don't see a benefit in typing those extra class names at all. I know the framework was written by some smart people I am sure this must be a part of the design philosophy but i don't agree with it. This is one of the main reasons I chose another framework for my project.
