### ISSUE TITLE
Responsive rollup doesn't contain responsive grids

### ISSUE THREAD

**Issue by wildlyinaccurate** [yahoo/pure#582]
The yahooapis responsive rollups referenced in the documentation (http://yui.yahooapis.com/pure/0.6.0/pure-min.css and http://yui.yahooapis.com/pure/0.6.0/pure.css) don't contain the responsive grids.

Is this intended? I would expect to see the same grids in those rollups which can be found in http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css.

**Comment by lkraav** [comment]
Yes, it's intentional. This past decision isn't super-intuitive, I agree, so will probably be reviewed for future releases. Doesn't guarantee a change in the process, but additional clarity will be provided for sure.

**Comment by wildlyinaccurate** [comment]
Okay, thanks for the clarification. I've just read the Grids documentation more closely and it's quite clearly stated there -- I must've just glossed over it.
