### ISSUE TITLE
Unable to add dropdown menu to "Responsive Horizontal-to-Vertical Menu"

### ISSUE THREAD

**Issue by olliefx** [yahoo/pure#587]
Hi Guys,

I have started a project using Purecss which I think is great by the way. I only wish there were more documentation and examples and custom themes you can purchase. I think it would push this great little css framework along.
The issue I am having is trying to get a dropdown working for the "Responsive Horizontal-to-Vertical Menu" http://purecss.io/layouts/tucked-menu-vertical/#, no matter what i try I cant get it working.
Does it not support dropdowns as I cant move ahead otherwise. Is there someone out there that has got this working is there a solution you can point me to or even someone willing to help. Thanx

**Comment by absalomedia** [comment]
Dropdowns were removed post 0.5.0 to 0.6 whilst other things got reconciled, if I remember correctly.

I'm investigating ways to put them back into the core Pure build so we can have better coverage long term.

**Comment by olliefx** [comment]
Any Idea how long this will take or have you got a hack I can use temporarily until things get reconciled. Thanx

**Comment by siogorman** [comment]
It supports dropdowns.

Change the overflow to visible in  .custom-wrapper
```
.custom-wrapper {
     overflow: visible;
}
```

and then add this into the menu where you want the dropdown.
```
<li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
            <a href="#" id="menuLink1" class="pure-menu-link">Contact</a>
            <ul class="pure-menu-children">
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Email</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Twitter</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Tumblr Blog</a></li>
            </ul>
        </li>
```

**Comment by absalomedia** [comment]
In further investigation I can confirm what @siogorman said.

I've managed to replicate a horizontal dropdown on the Responsive Horizontal to Vertical Menu. Still working on ways to have it do both horizontal & vertical dropdowns depending on media queries.

In the interim I've also verified dropdowns work even without the 'pure-menu-allow-hover' class as seen in this [gist](https://gist.github.com/absalomedia/67392e40fb9302a2b8f8a92b709e097b)

**Comment by alleyhector** [comment]
Pardon me if I am reading this incorrectly, but it sounds like if you are using "Responsive Horizontal-to-Vertical Menu" dropdowns will not work at mobile breakpoints? I realize this is over a year old so has this been fixed? I would hate to have to start over with a whole different menu, especially since we are using the pure grids etc, which I have liked so far.
