### ISSUE TITLE
[ASK] Why Pure Griding only include the pure-u-* only, I can't find pure-g

### ISSUE THREAD

**Issue by benyaminl** [yahoo/pure#589]
Why Pure Griding only include the pure-u-\* only, I can't find pure-g? even on the base min, I still can't find the file, please help. thanks.

**Comment by absalomedia** [comment]
Grids in Pure is built out of a combination of the Pure grids-core.css and the Rework Pure Grids componetry. In it's current edition at 0.6, there is a separate grids.css file you need to reference outside of the core minified file. This is most likely why you can't find it

**Comment by benyaminl** [comment]
@absalomedia okay, but I still not get it, then I should include it also before include this? 


    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">


?

**Comment by absalomedia** [comment]
The pure-g class exists in the current pure-min.css file as seen [here](http://yui.yahooapis.com/pure/0.6.0/pure-min.css). You need to include the base Pure CSS stylesheet before invoking the grids-responsive stylesheet,

The pure-g class is required before using any grid units ( pure-u-*). The reason the responsive grid only includes pure-u elements is that the unit elements are dynamically generated out of the Rework Pure Grids component.

**Comment by beefo** [comment]
Looks like for some reason the bower package is missing some required style sheets. I had to download the full pure.css file to get it to work.

**Comment by tedshd** [comment]
Hi
If you use some tool minify you CSS.
Maybe has some problem in this
Reference
http://blog.tedshd.io/posts/824645-gulp-one-problem-i-found-when-i-use-css-minify-with-some-css-library
