### ISSUE TITLE
Marketing Template - Can't change the .splash-container to a background image

### ISSUE THREAD

**Issue by ACreativeBender** [yahoo/pure#590]
When I try to change the background in the Marketing template to an image instead of the default image colour I can't get the image to show up. Anyone else have this issue. 

I can get the image to appear in my dreamweaver window, but when I view on my testing server it's not there? 

Any help would be appreciated!

**Comment by redonkulus** [comment]
This is a better question for stackoverflow.com instead of the issues here. If it is still an problem, please open one there. Thanks!
