### ISSUE TITLE
Normalize .pure-table {th,tfoot} -> text-align: left?

### ISSUE THREAD

**Issue by lkraav** [yahoo/pure#591]
I'm running into default alignment peculiarities in situations where `.pure-table tfoot th` elements are browser-defaulted to `text-align: center`.

**BACKGROUND RESEARCH**
http://stackoverflow.com/questions/11321065/th-text-align-compatibility
http://stackoverflow.com/questions/28306885/default-text-align-for-th-in-google-chrome
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th

We already have `.pure-table thead { text-align: left; }.

I'm proposing this should include `.pure-table tfoot`, too.

EDIT not sure about normalizing at `th` level. Thoughts welcome.

**Comment by absalomedia** [comment]
I see no problem with it. As pagination got dropped out of 0.6, it may actually help when using tfoot as part of the pagination area.

**Comment by redonkulus** [comment]
@lkraav my only reservation was treating `tfoot` the same stylistically as `thead`. Does it make sense that they should have the same treatment?

Alternatively, I would be fine just having a `tfoot` selector that sets the alignment to `left`.

**Comment by redonkulus** [comment]
Closed via https://github.com/lkraav/pure/commit/8b2226385786276773d5d09eeb1a1b9bda92d2b9
