### ISSUE TITLE
Build Process: Grunt v Gulp v Webpack v Browserify?

### ISSUE THREAD

**Issue by absalomedia** [yahoo/pure#592]
Currently the build process for Pure itself & the Pure core site is based on Grunt.  Yet most of what Grunt does is wrap other Node packages into it - Grunt Rework Pure Grids vs Rework Pure Grids for example. This seems unnecessary overhead.

What is the long term strategy post Yahoo for the build process:
- Grunt?
- Gulp?
- something else?

I've managed to develop a stable Gulp edition of the build process for Pure and may do something similar for the core Pure site (as it's running Express with Grunt).

**Comment by redonkulus** [comment]
Besides speed is there something else that Gulp will get us besides Grunt? I'm in favor of either way and when @lkraav gets time to work on this project, I suggested that he can optimize the build and release process any way he see's fit. 

If you want to share the work you have done that could be a good starting point too.

**Comment by augustblizzard** [comment]
maybe this should help https://github.com/gratimax/gulp-grunt

**Comment by absalomedia** [comment]
I've actually built a Gulpfile that builds Pure, without the need to use gulp-grunt
