### ISSUE TITLE
TextBox not formated OK

### ISSUE THREAD

**Issue by zm3** [yahoo/pure#593]
Hello,

I use pure css but now my form looks like this (Firefox, Chrome, Opera, Internet Explorer)
Why it keeps formated like that?

Sample of my code:
http://prntscr.com/cpv512

Form preview
http://prntscr.com/cpv4hd

Cumps,
Miguel

**Comment by geekosupremo** [comment]
It looks like you have it all stuck in a single 'row' in the grid.

It also looks like you're mixing your grid units in each of the elements.

What sort of layout are you trying to achieve?
