### ISSUE TITLE
A vertical menu with submenu doesn't work without javascript

### ISSUE THREAD

**Issue by eugenio11** [yahoo/pure#595]
According to the documentation you can get a vertical menu with a submenu working without javascript. I've copied the example I found here http://purecss.io/menus/ here is a simplified version that should work:
```
<html>
<head>
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="pure-menu custom-restricted-width">
    <ul class="pure-menu-list">
        <li class="pure-menu-item pure-menu-has-children ">
            <a href="#" id="menuLink1" class="pure-menu-link">More</a>
            <ul class="pure-menu-children">
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Autos</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Flickr</a></li>
            </ul>
        </li>
    </ul>
</div>
</body>
</html>
```
but it does't. Tested on Chrome and Firefox on Mac. Am I missing something?

**Comment by chaleybgis** [comment]
From the docs:

Even with JavaScript in place, you still might want to display submenus on hover. Just add pure-menu-allow-hover to the pure-menu-has-children list item. This can be nice for desktop users and provides a fallback for users with no JavaScript.

**Comment by eugenio11** [comment]
You are right, the example in the documentation shows pure-menu-allow-hover only for the horizontal menu and not for the vertical one, that's why I probably got confused. Thanks.
