### ISSUE TITLE
Decision - Pure or ...

### ISSUE THREAD

**Issue by dbasnett** [yahoo/pure#597]
I work for the Missouri General Assembly and have been tasked with redesigning this [site](www.moga.mo.gov).  A lot of mo.gov sites use bootstrap, and that might even be considered a standard.

When I compared pure v. bootstrap I didn't see the need for using bootstrap.  My biggest concern about pure is that I don't get that warm fuzzy feeling about it's future.  It also concerned me that the only 'scheme' tool I could find was not close to using the latest version of pure.  That could just be operator error.

I can choose bootstrap and be safe, or I can pick a better framework that most closely matches the limited needs I have.  Just not sure what to do.

FWIW - I have nothing to do with our current site.

**Comment by redonkulus** [comment]
@dbasnett you can take a look at [this thread](https://github.com/yahoo/pure/issues/557) for more up to date information. Pure in its current form is stable enough to use in production. But I can understand the hesitation. Hopefully more progress gets underway but I can't promise any timeframes as that has gotten me in trouble before :)

Closing this as a duplicate.

**Comment by dbasnett** [comment]
Why did you close this? The thread referenced is old, and I didn't get any input from end-users.
