### ISSUE TITLE
Use HTTPS CDN and resource integrity

### ISSUE THREAD

**Issue by fulldecent** [yahoo/pure#601]
Please use HTTPS for the CDN.

Currently at http://purecss.io/ the CSS resource is linked using HTTP and does not have resource integrity.

HTTP can be modified in transit by ISPs and governments. Yahoo has recently cooperated with a government in a way that users do not appreciate.

Bootstrap has an example of how to do this correctly and it resolves all the above concerns:

``` html
<link 
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"  
  integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
  crossorigin="anonymous"
>
```

**Comment by samwalls** [comment]
+1 as of now, the only "insecure" element I have on a page of mine (hosted with TLS via Caddy) is the inclusion of pure CSS. If it is possible to resolve this that would be great!

**Comment by KrisSiegel** [comment]
CDNJS supports SRI, SSL, etc and is free. Suggest dropping all from documentation but the one(s) that support SSL + SRI as the others should never be used in the first place. This also *slightly* simplifies the documentation :)

**Comment by redonkulus** [comment]
@KrisSiegel I haven't used SRI myself, is it something that CDN's have to integrate with or can we just rely on the browser to validate the integrity? From the [MDN doc](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), it seems like its the Browsers responsibility. Please correct my assumptions, thanks!

**Comment by KrisSiegel** [comment]
@redonkulus yeah the browser has the responsibility and, essentially, CDNs don't have to do anything to support it. But CDNJS and some others will give you the ability to copy the entire snippet of HTML that includes the SRI which cuts down on the friction of people actually using the feature.

I'm of the opinion that if you don't make it as easy to do the most secure thing as possible people won't do it. So, in my opinion, I'd stick to just the ones that do that but, barring that, at a minimum I'd drop any non-SSL ones at least.
