### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by fulldecent** [yahoo/pure#602]
You're ready. Please release a 1.0 version.

**Comment by kcomplexes** [comment]
Apologies for the noob intrusion. Is Pure likely to see any further updates? I have just started looking for minimal css project for a small community project I am working on. There doesnt appear to be any updates in quite some time.

**Comment by Goury** [comment]
@kcomplexes 
I sincerely doubt this

**Comment by kcomplexes** [comment]
@Goury 
Any suggestions for actively maintained and **minimal** css 'framework'/design template? Or  will Pure in its current state work 'as is' for simple designs?

I'm considering just using rolling an extremely  simple html/css soultion, as this is for a project for very remote/isolated communities where every mb counts.

Appreciate your response, thanks!

**Comment by Goury** [comment]
> an extremely simple html/css
Sounds like you can do it yourself, CSS is not that hard and basic HTML is very simple thing too.

As for me, I have not decided yet what to do with my projects that rely on Pure.
Options are either [fork and support Pure myself] (but yahoo should fuck itself with its rights reservation first) or [use minimal bootstrap] (but it is not as minimal as I like anyway, so changing dead not ideal solution to just not ideal doesn't sound too convincing) or [making my own minimalistic CSS framework] (for which I will require some funding).

**Comment by fulldecent** [comment]
I have reached out to Pure leadership asking if we can get a new release manager and keep the project ticking along.

**Comment by Goury** [comment]
@fulldecent
Have you reached their answer?

**Comment by redonkulus** [comment]
I'm on the thread and have responded. Hopefully we can work something out. More details on the potential handoff are in https://github.com/yahoo/pure/issues/557

**Comment by gliderguld** [comment]
Flipping the main version number to 1 would indicate production readiness but also that the project is still alive.

**Comment by drawcard** [comment]
Well I for one hope this project isn't dead. I've only just started using it in a bunch of projects and it's the best minimal CSS framework out there, a perfect counterpart to Bourbon / Neat. I do hope we see the project open up to the community and we can see more action on those 20+ pull requests sitting in the queue.

**Comment by tomjoad2000** [comment]
+1. Finding pure great, using it with great performance. It deserves a 1.0 release, maybe as a stripped fork with a roadmap.

**Comment by redonkulus** [comment]
I would imagine a 1.0 would make sense for the next time there is a breaking change, so I'm in favor of this. But would not do it until it is necessary.

**Comment by markotom** [comment]
Come on, turn the RC to first release! What else do you need to do that?

**Comment by guest20** [comment]
1.0 isn't a breaking release, that's not how 1.0 works. Other majors can be breaking, but for a 1.0 there's no previous major to break compatibility with,

**Comment by redonkulus** [comment]
@guest20 fair enough. In my mind 0.6.2 (current release) and 1.0.0 are the same thing but it having it as 1.0 gives developers/users some comfort, then I can do that. I guess making it 1.0 also makes it clear that there are no more breaking changes until 2.x.

**Comment by redonkulus** [comment]
@markotom @guest20 @fulldecent @tomjoad2000 

🎉🎉 Pure 1.0 has been released 🎉🎉 . Sorry for all the delays, better late than never.

**Comment by drawcard** [comment]
These are exciting times to be alive!

http://imgur.com/dqWJerV

Thanks for keeping the project going.
