### ISSUE TITLE
vertical submenu not working

### ISSUE THREAD

**Issue by darkworks** [yahoo/pure#604]
am trying to implement purecss vertical submenu , i tried but its not working , 

demo :: http://jsbin.com/sukitudino/edit?html,output

**Comment by siogorman** [comment]
You'll need to set a width on your menu, I've used the pure-u-x-x
I can't see the custom-menu-width you are using. I'd imagine you just needed to apply a width to it on the ul and it should have worked.
Sure it was just a copy and paste for test purposes but the pure-menu-link anchors had the same id,

If you paste the below into your sample it will work.

`<div class="pure-menu">
    <ul class="pure-menu-list pure-u-1-8 pure-u-sm-1-2">
        <li class="pure-menu-item pure-menu-selected"><a href="#" class="pure-menu-link">Flickr</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Messenger</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Sports</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Finance</a></li>
        <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
            <a href="#" id="menuLink1" class="pure-menu-link">More</a>
            <ul class="pure-menu-children">
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Autos</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Flickr</a></li>
                <li class="pure-menu-item pure-menu-has-children">
                    <a href="#" id="menuLink2" class="pure-menu-link">Even More</a>
                    <ul class="pure-menu-children ">
                        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Foo</a></li>
                        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Bar</a></li>
                        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Baz</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>
`

**Comment by darkworks** [comment]
ok thanks :)
