### ISSUE TITLE
Small error in one of the example layouts

### ISSUE THREAD

**Issue by guategeek** [yahoo/pure#611]
So I was using the example layout from this page:
http://purecss.io/layouts/side-menu/

but the CSS transition doesn't work on the main content of the page. The menu slides out with a nice animation but the page jumps out. To fix this we need to define `left: 0;` on the `#layout` class. This is because the default is auto, and an animation can't be created between auto and a value.

before:
`#layout {
    position: relative;
    padding-left: 0;
}`
after:
`#layout {
    position: relative;
    padding-left: 0;
    left: 0;
}`

**Comment by redonkulus** [comment]
@guategeek is this consistent across all browsers?

**Comment by siogorman** [comment]
@rednkulus Yes this is consistent across browsers, there is a transition rule in the css that never fires on  #layout which is what I believe @guategeek is referencing here.

**Comment by redonkulus** [comment]
@guategeek want to open a PR in the pure-site repo to fix?

**Comment by redonkulus** [comment]
@guategeek @siogorman I've gone ahead and fix this at https://github.com/yahoo/pure-site/commit/a3ce38fea1f1a5c725a28c93bf30294e83771ed8. Thanks for reporting!
