### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by albic7** [yahoo/pure#618]
I am new to GitHub and new in using Pure, so hope I am in the right place to ask for some help. :)

I am just trying to do my first page using pure, what I am stuck at the moment is in using pure-img for having responsive images, the image are responsive when in reduce the screen but when the screen become bigger and the image are supposed to increase from their original dimension they just stay static in their original size. 

Can you please help me :)

**Comment by tomjoad2000** [comment]
Unless it's a bug, you're in the wrong place. Try stackoverflow.com

**Comment by albic7** [comment]
Thanks
