### ISSUE TITLE
Enhancement request: Composer support

### ISSUE THREAD

**Issue by cxj** [yahoo/pure#623]
### Description

Would be nice if Pure supported being retrieved as a Composer package from Packagist, similar to other common web resources, such as jQuery.

**Comment by redonkulus** [comment]
Today we support Bower and NPM. But Bower support may be removed to just use NPM. I don't believe adding another package manager will happen in the foreseeable future, unless there is heavy demand. Thanks!

**Comment by redonkulus** [comment]
I've thought about this more. I'm actually not against a `composer.json` file since it helps support the PHP community. I would prefer to deprecate `bower` cause it duplicates a lot of what NPM already gives us. So in this case, I'm in favor of the `composer.json` file and will open a PR to add it.
