### ISSUE TITLE
Unwanted behavior with html class="hidden"

### ISSUE THREAD

**Issue by grenouille220** [yahoo/pure#627]
### Description

Conflict with default Modernizr

### Expected behavior
Current modernizr add a default hidden classname on the html element.
So adding as it is without customized settings: purecss + modernizr = voila !
The document element is now display none !important. Interesting :-/

### Actual behavior
Keep the root document element as it is please.
Suggestion: 
~~~css
html .hidden { display: none !important; }
~~~

### Steps to Reproduce

1. link rel="stylesheet" href="//cdn.jsdelivr.net/pure/0.6.2/pure-min.css"
2. script src="//cdn.jsdelivr.net/modernizr/3.3.1/modernizr.min.js"
3. Sayonara html !

Best

**Comment by redonkulus** [comment]
@grenouille220 Interesting use case. Is it possible to configure modernizr to not output the hidden class or possible change the name of the class?

**Comment by grenouille220** [comment]
@redonkulus yes shure custom build of modernizr is the default way to go. 
It's possible to remove the classname or add a custom prefix.
I suppose everyone does that, in a fresh start I just added it as it is.
Was a bit surprise, I'm still alive :-)

**Comment by redonkulus** [comment]
Ok cool. Ya, I don't think we would start adding `html` in the selectors, as keeping them as just classes makes it easier for people to override.
