### ISSUE TITLE
"go back" button causes problem

### ISSUE THREAD

**Issue by petermuller71** [yahoo/pure#628]
### Description
In IE Edge on a Window10 pc, there is unexpected and unwanted behavior, when you click on the 'go back' button. The former 'menu-item' has the css-hover background.
This can also be seen on purecss.io website (see: steps to reproduce)

### Expected behavior
The former menu-item, should not have the css-hover background, when you 'go back'.

### Actual behavior
the former menu-item gets a css-hover background when you click on the 'go back' button.

### Steps to Reproduce
1. go to: http://purecss.io/tools/ 
2. click on 'customize' in the navigation bar 
3. click on 'go back' button of the browser (IE Edge)
4. then you see:
    - tools-item is active (that is good)
    - customize-item has hover-background color (that is not good)

### Environment
IE EDGE on Windows10
(there is no problem on Chrome)
![pure](https://cloud.githubusercontent.com/assets/6226722/22079129/00989686-ddbb-11e6-9253-ba52a34daaae.jpg)

**Comment by redonkulus** [comment]
Please re-open this in the pure-site repo if it is still a concern. This is not a Pure specific issue and I would like to keep only library issues open here. Thanks!
