### ISSUE TITLE
Landing page example not displaying correctly on displays with low height

### ISSUE THREAD

**Issue by cpury** [yahoo/pure#633]
I've been adapting your landing page example, but realized it does not display reliably on displays with low height, e.g. phones in landscape mode.

Specifically, I mean the splash at the top. Look at this:

![screen shot 2017-02-22 at 3 12 49 pm](https://cloud.githubusercontent.com/assets/1777905/23202634/6e9f26c4-f911-11e6-87e7-4736649126e5.png)
^ Correct display of splash.

![screen shot 2017-02-22 at 3 12 55 pm](https://cloud.githubusercontent.com/assets/1777905/23202635/6ecda422-f911-11e6-951f-dcce70570e2e.png)
^ Splash is cut off, button can not be clicked.

IMO, that's pretty bad for an example of how to use your framework, so you might consider fixing that.

**Comment by redonkulus** [comment]
The spacing above the big bold text needs to be adjusted. Feel free to open a PR in the pure-site repo. I'm going to close this since it's not a Pure issue.
