### ISSUE TITLE
problem with responsive pure-input-*

### ISSUE THREAD

**Issue by hpsoar** [yahoo/pure#636]
<img width="395" alt="screen shot 2017-03-01 at 5 49 45 pm" src="https://cloud.githubusercontent.com/assets/1549522/23454589/b1bb9910-fea7-11e6-9d1a-b07bf38a73da.png">

As shown, I set the input class to 'pure-input-3-4' and it looks good

However, when I drag the browser narrower, it looks as below:

<img width="355" alt="screen shot 2017-03-01 at 5 50 17 pm" src="https://cloud.githubusercontent.com/assets/1549522/23454647/e875bb3e-fea7-11e6-848c-c8da4c64e0e6.png">

How should I make it look better?

The main problem is that the titles are not aligned left.

PS:
At the same time I have a responsive left-panel, after further narrow the browser and make the left-panel disappear, the result looks better

<img width="347" alt="screen shot 2017-03-01 at 5 57 07 pm" src="https://cloud.githubusercontent.com/assets/1549522/23454841/8f2af796-fea8-11e6-8dd2-4e907a9b2434.png">

If possible I also want the text input control can be responsive, in the above image, it should become pure-input-1-1

**Comment by redonkulus** [comment]
@hpsoar you should be able to use responsive grids to achieve what you want https://purecss.io/grids/#pure-responsive-grids
