### ISSUE TITLE
Add the not-allowed cursor to disabled things

### ISSUE THREAD

**Issue by lffg** [yahoo/pure#637]
Hey!
Why you don't add the:
`cursor: not-allowed;`
to the disabled things?

**Comment by Goury** [comment]
Because we should not, this will only cause frustration and solve nothing

**Comment by lffg** [comment]
Okay,  you're right. ;D

**Comment by KrakenEXE** [comment]
Valid points, this should be closed.

**Comment by redonkulus** [comment]
Closing 👍
