### ISSUE TITLE
Accessible menus

### ISSUE THREAD

**Issue by jsha** [yahoo/pure#639]
### Description

We use menus with classes `pure-menu-item pure-menu-has-children pure-menu-allow-hover`. These menus open correctly on hover, but if a user focuses the menu item by hitting Tab, the menu does not open. This is an accessibility problem for people who can't use a mouse.

### Expected behavior

Selecting a menu with Tab should open the menu, and subsequent Tabs should select menu items.

### Actual behavior

Selecting a menu with Tab does nothing.

### Steps to Reproduce

Any example .html file reproduce the problem is attached.

### Environment
* Pure version: 0.6.2
* Browser name and version: Google Chrome
* Link to your project or example: https://letsencrypt.org/. See also attached simplified HTML.
[test.html.txt](https://github.com/yahoo/pure/files/848607/test.html.txt)

**Comment by redonkulus** [comment]
Is there a solution that works without JS? I saw this commit referenced from the issue above https://github.com/letsencrypt/website/commit/81f12157ec25f860fe43df05c625ea3359f7f67f

**Comment by redonkulus** [comment]
Please re-open this in the pure-site repo if it is still a concern. This is not a Pure specific issue and I would like to keep only library issues open here. Thanks!

**Comment by jsha** [comment]
Unfortunately, it seems there is no technique to implement this without
JavaScript.

**Comment by redonkulus** [comment]
Ok good to know. We will leave this up to the app owners to implement.
