### ISSUE TITLE
building within a scope

### ISSUE THREAD

**Issue by dkorobov** [yahoo/pure#642]
### Description

Building in scope

### Expected behavior
given a ccs source in say less or sass or anything else really we would gain ability to build pure for a given scope. As an example i have a requirement to avoid any possible collisions and have my style applicable to the parent tag of div#doccontent. It is laborious to do this by hand working with css.

**Comment by dkorobov** [comment]
looks like i might be able to do with gulp on the side actually

**Comment by redonkulus** [comment]
@dkorobov Pure already uses the 'pure-' namespace to help prefix selectors. You even have the option to modify this yourself via a Grunt or Rework plugin: https://purecss.io/tools/#mutating-selectors
