### ISSUE TITLE
https://unpkg.com/purecss@0.6.2/build/pure-min.css does not include normalize package

### ISSUE THREAD

**Issue by I-CRE8** [yahoo/pure#643]
When using the cdn version of pure `<link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/pure-min.css" integrity="sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD" crossorigin="anonymous">` as per https://purecss.io/ it doesn't appear to include normalize although the copyright statements appear the actual css does not.

**Comment by redonkulus** [comment]
@I-CRE8 I see it inside pure-min.css. Am I missing something? 

> ...html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}...

**Comment by I-CRE8** [comment]
You are correct I was confused because the code is not in the same order. Apologies
