### ISSUE TITLE
css  Grammatical errors  ？？？

### ISSUE THREAD

**Issue by cws999** [yahoo/pure#646]
https://github.com/yahoo/pure/blob/master/src/grids/tests/manual/responsive.html
Line 11，Add at the end “<!-->“？？？？？
I just started learning css

**Comment by redonkulus** [comment]
I believe the `<!-->` isn't needed on line 14. Not sure why that was added originally.

**Comment by redonkulus** [comment]
You read more about it here: https://www.quirksmode.org/css/condcom.html

I've removed it https://github.com/yahoo/pure/commit/2fde4e7985335f09aac0ede5c7fa0c63b456a578
