### ISSUE TITLE
Text in <select> vertically cropped

### ISSUE THREAD

**Issue by TheRealMarnes** [yahoo/pure#652]
I keep running into this issue with dropdowns, in my personal project but purecss.io as well. The text is "pqD" and the bottom of the letters keeps getting chopped off.

![image](https://cloud.githubusercontent.com/assets/3950300/26739625/d5dbba0e-47d2-11e7-8a08-b0eae7b54079.png)
![image](https://cloud.githubusercontent.com/assets/3950300/26739790/7d5e7f50-47d3-11e7-93cf-26e63398fc2b.png)

I have specific personal font settings in chrome that are likely to be blamed, but it's my belief that browsers and css frameworks are supposed to cope with that by design. No?

![image](https://cloud.githubusercontent.com/assets/3950300/26739724/43eb6ae4-47d3-11e7-8724-8169cde01f40.png)

**Comment by redonkulus** [comment]
@TheRealMarnes if you open the same page in a different browser or profile, without your custom settings, does the text still get cut off?

**Comment by TheRealMarnes** [comment]
It worked fine in chrome at work where I don't think I have custom fonts set (I may have but I clearly remember it looked fine there, whereas I don't specifically recall customising my fonts).

But I also have vivaldi open right now, where I have no custom fonts set, and it does the same thing.

![image](https://cloud.githubusercontent.com/assets/3950300/26740821/66bd3292-47d7-11e7-8456-b085449d64ea.png)
![image](https://cloud.githubusercontent.com/assets/3950300/26740824/67bbf84a-47d7-11e7-9970-6074b86fa2bb.png)

**Comment by TheRealMarnes** [comment]
Same thing in edge: 
![image](https://cloud.githubusercontent.com/assets/3950300/26741174/98798a82-47d8-11e7-928c-33464997fdd5.png)

**Comment by iscraft** [comment]
try this
pure.css find .pure-form select{height:2.25em;border:1px solid #ccc;background-color:#fff}
add padding-top:0.2em
![2017-07-07_171023](https://user-images.githubusercontent.com/5448825/27951522-d6564a82-6337-11e7-9f3d-9cbf8d4370ff.jpg)
![2017-07-07_170907](https://user-images.githubusercontent.com/5448825/27951530-dbaae650-6337-11e7-8bc1-5c25118cf92b.jpg)

**Comment by redonkulus** [comment]
I'd prefer that sites override the default style to accommodate any custom settings that may be enabled. Something similar to what @iscraft would suffice.

**Comment by TheRealMarnes** [comment]
@redonkulus but 2 of the 3 sample cases don't even have custom settings, they're on all defaults
