### ISSUE TITLE
Use svg instead of icon fonts

### ISSUE THREAD

**Issue by stephenbe** [yahoo/pure#657]
Hello,

I was wondering why use icon fonts instead of svg? I could not find any issue on this subject.

Thanks!

**Comment by redonkulus** [comment]
Probably just based on when it was coded. Back a few years ago icon fonts were the preferred method; nowadays its svg. Could've also been because of browser support at that time. Not really sure, I do not have the history on it.

**Comment by stephenbe** [comment]
Any talks to change it to svg?

**Comment by redonkulus** [comment]
I wouldn't be against it. BTW, this issue probably belongs in the pure-site repo since its related to that.

**Comment by redonkulus** [comment]
Please re-open this in the pure-site repo if still needed. Thanks!

**Comment by lkraav** [comment]
I don't know - I recently switched to Material Icon Font and couldn't be happier. 

Quoting http://google.github.io/material-design-icons/

> Using the font is not only the most convenient method, but it is efficient and looks great:
> 900+ icons all from a single, small file.
> Served from Google Web Font servers or can be self hosted.
> Supported by all modern web browsers.
> Colored, sized and positioned entirely with CSS.
> Vector-based: Looks great at any scale, retina displays, low-dpi display screens.
