### ISSUE TITLE
Footer doesn't get pushed to the bottom on Blog layout

### ISSUE THREAD

**Issue by paambaati** [yahoo/pure#658]
### Description

In Blog layout, the footer doesn't stay on the bottom if the page has only one post.

### Expected behavior
The footer should stay on the bottom if the page's has little content.
![Imgur](http://i.imgur.com/UAVUyc1.png)

### Actual behavior
![Imgur](http://i.imgur.com/PyKJ1Qp.png)

### Steps to Reproduce

1. Use the 'Blogs' layout at https://purecss.io/layouts/blog/
2. Remove all but 1 post.
3. Take a look at the footer.

### Environment

* Pure version: 1.0.0
* Browser name and version: Chrome 61.0.3141.7
* Link to your project or example: NA

**Comment by redonkulus** [comment]
Thanks for the report. Feel free to open a PR to fix this. Also, this issue probably makes more sense in the pure-site repo.

**Comment by paambaati** [comment]
Thanks! I've cross-posted to the `pure-site` repo.
