### ISSUE TITLE
abbr underline problem

### ISSUE THREAD

**Issue by aytacyildiz** [yahoo/pure#663]
There is two dotted underline for HTML `abbr` elements.

Screen shoot:
![screenshot_2017-07-22_19-12-33](https://user-images.githubusercontent.com/1824240/28492837-4c39a528-6f13-11e7-87d3-0d4f15cf1d2c.png)

HTML I'm using:
```html
<!DOCTYPE html>
<html>
<head>
	<title>abbr test</title>
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
</head>
<body>
<p>The <dfn id=whatwg><abbr
title="Web Hypertext Application Technology Working Group">WHATWG</abbr></dfn>
is a loose unofficial collaboration of Web browser manufacturers and
interested parties who wish to develop new technologies designed to
allow authors to write and deploy Applications over the World Wide
Web.</p>
</body>
</html>
```

**Comment by redonkulus** [comment]
Is that just the browsers default styling for abbr? Is it consistent across browsers?

**Comment by aytacyildiz** [comment]
@redonkulus mozilla says this: https://developer.mozilla.org/en/docs/Web/HTML/Element/abbr#Default_styling
As far I know this isn't suppose to be happen.
I tried with Firefox, Chrome, Edge, Internet Explorer. And saw two underline in Firefox and Chrome. One underline in Edge and Internet Explorer.
You can use this link to check: https://jsfiddle.net/f7ve3vb9/

**Comment by magikstm** [comment]
This is an upstream issue in normalize.css.

pure.css currently use normalize.css version 3.0.3 on jsfiddle (latest of the 3.0 branch).

It was corrected in this commit: https://github.com/necolas/normalize.css/commit/5304c784ffbd03da265fcbf7bf49f6964cbcfc9c

It was delivered in normalize 4.0.0 (March 19, 2016):
https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md#400-march-19-2016

**Comment by magikstm** [comment]
#513 is related to this and potentially a duplicate.

**Comment by aytacyildiz** [comment]
Then I will add this lines to my website in order to solve this issue: https://github.com/mtsar/mtsar.github.io/commit/73bb06363aa42d28d123b0f1cbc81a1183a38d6e

Maybe in the future we have more recent version of Normalize in Pure project.

Or is this just a CDN thing?

Can we have more recent version of Normalize with Pure v1.0.0?

I'm sorry with my English. I hope you understand what I mean.

**Comment by redonkulus** [comment]
@aytacyildiz I'm going to close in favor of #513. I think for now adding it your site is the most practical solution. Upgrading normalize is something we should do, it will just require a bit of testing across browsers.
