### ISSUE TITLE
.pure-g missing flex-flow attribute

### ISSUE THREAD

**Issue by jamesaspence** [yahoo/pure#664]
### Description

pure-g styling has flex-flow styling with both the -webkit- and -ms- prefixes, but not vanilla `flex-flow`. This might be a mistake on our end of how pureCSS should work, but this seems like an oversight.

### Expected behavior
`flex-flow` would be set properly with and without the prefixes, i.e.
```scss
flex-flow: row wrap;
-webkit-flex-flow: row wrap;
-ms-flex-flow: row wrap;
```

### Actual behavior
`flex-flow` is instead only set through the following styles:
```scss
-webkit-flex-flow: row wrap;
-ms-flex-flow: row wrap;
```

### Steps to Reproduce

1. Install pureCSS (^0.6.0, also present on 1.0.0)
2. Add pure-g class to some HTML (i.e. `<div class="pure-g"><div>Test 1</div><div>Test 2</div></div>`
3. Check styles to see missing default `flex-flow` attribute

### Environment

* Pure version: 0.6.2 (tested on 1.0.0
* Browser name and version: Chrome 59.0.3071.115
* Link to your project or example: N/A (internal company project)

**Comment by vannitotaro** [comment]
Hi @jamesaspence, new Pure user here. :smiley: 

Pure 1.0.0 source code sets only `flex-flow: row wrap` (see [grid-core.css:29](https://github.com/yahoo/pure/blob/v1.0.0/src/grids/css/grids-core.css#L29) and [this commit](https://github.com/yahoo/pure/commit/7c63e1185bec499b994da281ef54918b9131929e#diff-5c096db065dc4ee970eae7735a523992L28) that removes manual vendor prefixes).

The grunt build process then [uses `autoprefixer`](https://github.com/yahoo/pure/blob/master/Gruntfile.js#L112) to add vendor prefixes according to the specified browser compatibility options.

The final build result is 
```
    -webkit-flex-flow: row wrap;
        -ms-flex-flow: row wrap;
            flex-flow: row wrap;
```
(see https://unpkg.com/purecss@1.0.0/build/pure.css row 496).

Maybe the Chrome dev tools let you see only the "valid for that browser" styles.
So I think that this is not a bug and you could close the issue.

Have a great day!

**Comment by jamesaspence** [comment]
Hi @vannitotaro, if this was just a matter of this style not appearing in the chrome dev tools specifically that'd be fine, I wouldn't have noticed. However, flex-flow is definitely not being applied correctly here. I had to manually apply that property myself, because a large chunk of this internal site was busted due to this.

Could this be to some sort of incompatibility with our local autoprefixer, perhaps?

**Comment by vannitotaro** [comment]
> Could this be to some sort of incompatibility with our local autoprefixer, perhaps?

@jamesaspence yes I think it is possible because, as you can see from v1.0.0 final build source, all three definitions are there for sure.

Just to be ultra-sure, I checked the minified version too, and all three *flex-flow are there.

**Comment by vannitotaro** [comment]
It is the unprefixed `flex-flow` that you cannot find  in production, so probably your autoprefixer is configured for an old Chrome version that needed the prefixed version, so the unprefixed version disappears.

Anyway I think that it is not related to the codebase of Pure, so you can close this issue.

**Comment by jamesaspence** [comment]
Closing - this appears to be an issue with our local autoprefixer. Thanks for the help guys!

**Comment by NiB18** [comment]
Just had a similar problem which turned out to be outdated version of pureCSS. Project has been using [0.6.0](https://github.com/yahoo/pure/releases/tag/v0.6.0)  which didn't have unprefixed version of flex-flow

**Comment by jamesaspence** [comment]
@NiB18 updating to 1.0 resolved it? That's strange - mine was not resolved after updating. I guess I'll need further testing on my end.

**Comment by NiB18** [comment]
In that case I think it will be your processing setup.
