### ISSUE TITLE
CDN does not return a grids-responsive-min.css file

### ISSUE THREAD

**Issue by umpox** [yahoo/pure#665]
### Description
The unpkg.com CDN is suddenly not providing the responsive grids file

### Expected behavior
CSS file should be returned from https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css

### Actual behavior
"Cannot find file "/build/grids-responsive-min.css" in package purecss@1.0.0"

### Steps to Reproduce
Access https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css

**Comment by MartinKolarik** [comment]
Lots of people have been complaining about random 404 and 503 unpkg responses recently. You can always use jsDelivr instead, which works in a similar way but is more reliable: https://cdn.jsdelivr.net/npm/purecss@1.0.0/build/grids-responsive-min.css

**Comment by redonkulus** [comment]
Please feel free to open a ticket with unpkg.com if you see consistent issues. They should be able to help. Agree with @MartinKolarik that you can always use an alternative CDN or host them on your own. Going to close this since its not an issue for Pure itself.

**Comment by umpox** [comment]
@redonkulus For what its worth this has broken some documentation examples on https://purecss.io itself. 

E.g. See 'An example of pure responsive grids' at https://purecss.io/grids/

It might be worth updating your own site to use an alternative CDN too.
