### ISSUE TITLE
https://purecss.io SSL is broken

### ISSUE THREAD

**Issue by ANSI-C** [yahoo/pure#666]
### Description

https://purecss.io has broken SSL conf, http://purecss.io gives error 500

### Expected behavior
be able to browse the site

### Actual behavior
site unusable/unreachable

**Comment by redonkulus** [comment]
@ANSI-C thanks for the report. This is part of the ongoing Now.sh outage: https://twitter.com/zeit_status/status/897775014396743680

When we know more from them, we will update this ticket.

**Comment by okuryu** [comment]
backed to normal now.

**Comment by ANSI-C** [comment]
Thank you!
