### ISSUE TITLE
Left side menu uncleanliness during chrome hide on scroll

### ISSUE THREAD

**Issue by sgserg** [yahoo/pure#667]
### Description

When scrolling up on a page with open left side menu (including the main page), there is a glitch causing temporary white area under the menu during chrome hiding.

During scroll: (red line for mark up)
![img_0664](https://user-images.githubusercontent.com/5439847/29777846-19af4bec-8c16-11e7-813f-5983aa45c0a0.PNG)

Same area when scrolling stops:
![img_0665](https://user-images.githubusercontent.com/5439847/29777847-1a04b938-8c16-11e7-9ebc-f2ddbb271f87.PNG)

### Expected behavior

The whole area under menu is of solid dark color, and it is probably meant to remain this way at all times. Looks like a glitch.

### Actual behavior

White stripe shows up until scrolling stops.

### Steps to Reproduce

1. Open any page with left side menu (iPad, portrait mode), click to open the menu
2. Make sure chrome is full height 
3. Drag the page up to scroll and hide the chrome
4. Observe a white stripe appear under menu area on the bottom left.
5. When done scrolling, observe the stripe disappear.

### Environment

* Pure version: whatever is online at this date
* Browser name and version: Safari, iOS 10.3.3. iPad mini retina
* Link to your project or example: purecss landing page

**Comment by sgserg** [comment]
Similar thing happens on chrome hide/show in mobile landing page layout (https://purecss.io/layouts/marketing/) "Big Bold Text" box text jumps at the end of the scroll, both when chrome hides (scroll down) and when chrome appears (scroll up)

**Comment by redonkulus** [comment]
Thanks for the report. Please reopen this issue in the pure-site if still needed.
