### ISSUE TITLE
docs chapter "Understand pure grids" wrong code example

### ISSUE THREAD

**Issue by gitbreaker222** [yahoo/pure#671]
### Description

See live website: https://purecss.io/start/#understand-pure-grids:

> Pure's grid system is very simple. You create a row by using the .pure-g class, and create columns within that row by using the pure-u-* classes.
> 
> Here's a grid with three columns:
> 
> `<meta name="viewport" content="width=device-width, initial-scale=1">`

### Expected behavior

Some code with grids

### Actual behavior

Shows code from example above "Add the Viewport Meta Element"

Maybe this can be updated - just a small fix to prevent confusion :smiley_cat:

**Comment by redonkulus** [comment]
It looks ok to me. What browser are you seeing this in? Can you post a screen shot?

**Comment by gitbreaker222** [comment]
hm now when I open up, it actually looks all right too. Never mind I guess :confused:
_Latest Vivaldi 1.11.917.43 (Stable channel) (64-Bit) on Linux Mint 18_
