### ISSUE TITLE
How to trigger pure css when doing a ajax request

### ISSUE THREAD

**Issue by mrCPUgeek** [yahoo/pure#674]
### Description

Everything works fine, except when I send data back to the page thru an ajax request.  Is there a way to trigger the pure css when loading a element thru an ajax call?

### Expected behavior
When html data comes back from ajax request with pure css, I want it to look right.

### Actual behavior
The html does not have the pure css look when it comes back thru an ajax request.

### Steps to Reproduce

Create a web page with pure css and jquey.  do an ajax request of a page with pure css on the page that comes back.

**Comment by magikstm** [comment]
I see no reason for it to not work. Purecss is a css framework and shouldn't interfere with calls.

Please post your entire code.

**Comment by redonkulus** [comment]
Yes please reopen when more information is collected. Thanks!
