### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by KSuttle-cng** [yahoo/pure#676]
https://purecss.io/

<img width="390" alt="screen shot 2017-10-20 at 1 55 14 pm" src="https://user-images.githubusercontent.com/29458877/31835116-59d49fcc-b59e-11e7-846f-b766ff76fe02.png">

**Comment by redonkulus** [comment]
Looks to be related to the Now.sh outage 

https://twitter.com/zeit_status/status/921386950355013632

**Comment by okuryu** [comment]
backed to normal.
https://zeit-status.co/

**Comment by redonkulus** [comment]
Working for me too.

**Comment by KSuttle-cng** [comment]
Yep. Thanks all.
