### ISSUE TITLE
Docs show the wrong code for responsive image example

### ISSUE THREAD

**Issue by mccambridge** [yahoo/pure#688]
### Description

On https://purecss.io/base/#extras, notice the code block under *Responsive Images* is the same as the *Hiding Elements* section.

### Expected behavior
It should show a code block explaining how to make responsive images work.

### Actual behavior
See above.

### Steps to Reproduce

1. Go to https://purecss.io/base/#extras
2. Read the page.

**Comment by redonkulus** [comment]
This is working for me. Is this a problem for you? I can reopen if it is.

**Comment by zemlanin** [comment]
_Responsive Images_ code snippet still repeats the one for _Hiding Elements_

<img width="1004" alt="incorrect code snippet" src="https://user-images.githubusercontent.com/711514/73016921-7ffaa200-3e27-11ea-8899-0929f53ee768.png">

**Comment by redonkulus** [comment]
I believe your screenshot, I just don't understand why I'm getting a different thing:
<img width="754" alt="Screen Shot 2020-01-23 at 12 57 28 PM" src="https://user-images.githubusercontent.com/193272/73023271-04c1cd80-3de0-11ea-883d-e594eb9aba29.png">

Perhaps there is an old Now deployment that gets used from time to time.
