### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by Boscop** [yahoo/pure#690]
[Here](https://github.com/pimbrouwers/purecss-utils) it says:
> Since PureCSS is no longer being maintained, please checkout Hydrogen which has esstentially the same feature coverage as Pure as is being actively maintained!

Is it true that PureCSS is no longer being maintained?

Should we use a different css framework for new projects in production?

**Comment by DanielSt** [comment]
I am having the same question right now.

**Comment by Florian-R** [comment]
See #557

**Comment by krisbaehr** [comment]
Thanks, I was wondering about this too. It looks like it would be pretty easy to port to Hydrogen-css.

**Comment by pimbrouwers** [comment]
Howdy!

I can attest to the port being straight-forward.

I also maintain the repo very actively. So should you encounter any issues I can normally have it fixed and deployed in less than 1hr.

Thanks for checking it out!

**Comment by redonkulus** [comment]
Here is a more specific plan https://github.com/yahoo/pure/issues/557#issuecomment-358706553

Closing this in favor of the other ticket.
