### ISSUE TITLE
Dropdown Menu design tweak

### ISSUE THREAD

**Issue by adapterik** [yahoo/pure#98]
I was playing with the dropdown menu, creating a simple little set of dropdown menus, driven by a very small bit of javascript. It was also an exercise in building a static set of the menus in different states. 

That is when I discovered that the the sub menus are set up to be positioned absolutely. The effect is that when you turn them on (with pure-menu-open), they will overlap with the menu button that is supposed to open them. This is because the container for each is the parent.

The impact is that javascript *must* position the sub menu in order for the menu to work. Since javascript is required in order for the menu to operate (even if it is just a few lines) I have an alternate solution.

My proposal is that the sub menu be positioned with "position: relative" so that it stays in the flow of the menu, in relation to the menu button that invoked it. The result is that it does not overlap the menu button that invoked it, but appears just below it. (Don't worry, the sub menu list is still absolute so that it does not bump things around.) This is not an necessarily an optimal position for the sub menu, but it is a much better default position than overlapping.

More details below show how it would work.

(BTW I have a fork of pure on which I'll be experimenting with this, but I wanted to get this suggestion out there for opinion first.)

To be more specific, the structure of a menu is approximately:
````
menu
  menu-item (<li>)
    menu-label (<a>)
    menu-children (<ul>)
       menu-item (li item in menu
          menu-label (anchor tag)
            menu-children (ul list)
````
It is the menu-children ul that overlaps the menu-label anchor button.
My proposal would change the structure to this (again, approximately, there is more going on of course, and I've not experimented enough nor suggesting any specific naming -- but I know that this works.)
````
menu
  menu-item (<li>)
    menu-label (<a>)
    menu-children-container (<div>)
      menu-children (<ul>)
         menu-item (li item in menu
            menu-label (anchor tag)
            menu-children-container (<div>)
              menu-children (ul list)
````
The change is the addition of a "menu-children-container" to wrap the menu-children, which is the sub-menu. The menu-children-container is ```position: relative```, the ul inside is still absolute. This container is relative, but takes up no space, so it does not cause any interruption in the menu (if you just make the ul  position relative, it takes up space in the flow and the menu layout is messed up.)

The effect is that the sub-menu will open up immediately below the menu button that invoked it. For horizontal menus, this works fine as a default location to open up. css tweaks can make this more attractive (e.g. offsetting to the right a bit for sub sub menus). I've not tinkered with vertical menus yet, but usually you want vertical menus to open to the right.

Of course the menu-children-container could be set as position: absolute and behave exactly as it does now. And perhaps it is better if menu-children is the name of the container, and the actual list of children is menu-children > ul. That is what I mean by not having experimented enough!

Anyway, the idea is that this enables the menu to provide a better default position for sub menus. Javascript can still override this of course and position the sub menu in more sophisticated ways. The menu widget used on the pure doc site example, for instance, sets the sub-menu position based partly on the space available in the viewport (it is a little disconcerting to see a drop-DOWN menu drop-UP, but that is the widget designer's choice!).

It could be argued that since js is required to have a workable dropdown menu anyway, why bother saving a little bit of javascript work at the cost of the extra html complexity. I could argue that the change makes the job of the javascript tinkerer easier. Or that it would be great if the dropdown menus could be opened purely with css. Or that it is better for world peace to follow the rule of least surprise.

**Comment by jamesalley** [comment]
I have completely reworked the menus for Pure 0.6. You can check it out now by working off of Master branch or you can wait for me to cut the release candidate branch-- either way, I hope you really like the new menu construct, and are inspired by the sample JavaScript I provide.

Even though you filed this issue a long time ago, I hope that you will review the new menu construct and provide similar detailed, critical feedback. I look forward to it. In the meantime, I'm closing this as an open issue. Rest assured many of the issues you mention here have been addressed; some others will simply no longer be relevant.
